// Code generated by MockGen. DO NOT EDIT.
// Source: internal\rhythm\rythm.go

// Package rhythm is a generated GoMock package.
package rhythm

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/jodi-ivan/numbered-notation-xml/internal/entity"
	musicxml "github.com/jodi-ivan/numbered-notation-xml/internal/musicxml"
)

// MockRhythm is a mock of Rhythm interface.
type MockRhythm struct {
	ctrl     *gomock.Controller
	recorder *MockRhythmMockRecorder
}

// MockRhythmMockRecorder is the mock recorder for MockRhythm.
type MockRhythmMockRecorder struct {
	mock *MockRhythm
}

// NewMockRhythm creates a new mock instance.
func NewMockRhythm(ctrl *gomock.Controller) *MockRhythm {
	mock := &MockRhythm{ctrl: ctrl}
	mock.recorder = &MockRhythmMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRhythm) EXPECT() *MockRhythmMockRecorder {
	return m.recorder
}

// AdjustMultiDottedRenderer mocks base method.
func (m *MockRhythm) AdjustMultiDottedRenderer(notes []*entity.NoteRenderer, x, y int) (int, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdjustMultiDottedRenderer", notes, x, y)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// AdjustMultiDottedRenderer indicates an expected call of AdjustMultiDottedRenderer.
func (mr *MockRhythmMockRecorder) AdjustMultiDottedRenderer(notes, x, y interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdjustMultiDottedRenderer", reflect.TypeOf((*MockRhythm)(nil).AdjustMultiDottedRenderer), notes, x, y)
}

// SetRhythmNotation mocks base method.
func (m *MockRhythm) SetRhythmNotation(noteRenderer *entity.NoteRenderer, note musicxml.Note, numberedNote int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRhythmNotation", noteRenderer, note, numberedNote)
}

// SetRhythmNotation indicates an expected call of SetRhythmNotation.
func (mr *MockRhythmMockRecorder) SetRhythmNotation(noteRenderer, note, numberedNote interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRhythmNotation", reflect.TypeOf((*MockRhythm)(nil).SetRhythmNotation), noteRenderer, note, numberedNote)
}
