// Code generated by MockGen. DO NOT EDIT.
// Source: internal\rhythm\rhythm.go

// Package rhythm is a generated GoMock package.
package rhythm

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/jodi-ivan/numbered-notation-xml/internal/entity"
	musicxml "github.com/jodi-ivan/numbered-notation-xml/internal/musicxml"
	canvas "github.com/jodi-ivan/numbered-notation-xml/utils/canvas"
)

// MockRhythm is a mock of Rhythm interface.
type MockRhythm struct {
	ctrl     *gomock.Controller
	recorder *MockRhythmMockRecorder
}

// MockRhythmMockRecorder is the mock recorder for MockRhythm.
type MockRhythmMockRecorder struct {
	mock *MockRhythm
}

// NewMockRhythm creates a new mock instance.
func NewMockRhythm(ctrl *gomock.Controller) *MockRhythm {
	mock := &MockRhythm{ctrl: ctrl}
	mock.recorder = &MockRhythmMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRhythm) EXPECT() *MockRhythmMockRecorder {
	return m.recorder
}

// AdjustMultiDottedRenderer mocks base method.
func (m *MockRhythm) AdjustMultiDottedRenderer(notes []*entity.NoteRenderer, x, y int) (int, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdjustMultiDottedRenderer", notes, x, y)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// AdjustMultiDottedRenderer indicates an expected call of AdjustMultiDottedRenderer.
func (mr *MockRhythmMockRecorder) AdjustMultiDottedRenderer(notes, x, y interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdjustMultiDottedRenderer", reflect.TypeOf((*MockRhythm)(nil).AdjustMultiDottedRenderer), notes, x, y)
}

// RenderBeam mocks base method.
func (m *MockRhythm) RenderBeam(ctx context.Context, canv canvas.Canvas, notes []*entity.NoteRenderer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderBeam", ctx, canv, notes)
}

// RenderBeam indicates an expected call of RenderBeam.
func (mr *MockRhythmMockRecorder) RenderBeam(ctx, canv, notes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderBeam", reflect.TypeOf((*MockRhythm)(nil).RenderBeam), ctx, canv, notes)
}

// RenderBezier mocks base method.
func (m *MockRhythm) RenderBezier(set []SlurBezier, canv canvas.Canvas) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderBezier", set, canv)
}

// RenderBezier indicates an expected call of RenderBezier.
func (mr *MockRhythmMockRecorder) RenderBezier(set, canv interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderBezier", reflect.TypeOf((*MockRhythm)(nil).RenderBezier), set, canv)
}

// RenderSlurTies mocks base method.
func (m *MockRhythm) RenderSlurTies(ctx context.Context, canv canvas.Canvas, notes []*entity.NoteRenderer, maxXPosition float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderSlurTies", ctx, canv, notes, maxXPosition)
}

// RenderSlurTies indicates an expected call of RenderSlurTies.
func (mr *MockRhythmMockRecorder) RenderSlurTies(ctx, canv, notes, maxXPosition interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderSlurTies", reflect.TypeOf((*MockRhythm)(nil).RenderSlurTies), ctx, canv, notes, maxXPosition)
}

// SetRhythmNotation mocks base method.
func (m *MockRhythm) SetRhythmNotation(noteRenderer *entity.NoteRenderer, note musicxml.Note, numberedNote int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRhythmNotation", noteRenderer, note, numberedNote)
}

// SetRhythmNotation indicates an expected call of SetRhythmNotation.
func (mr *MockRhythmMockRecorder) SetRhythmNotation(noteRenderer, note, numberedNote interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRhythmNotation", reflect.TypeOf((*MockRhythm)(nil).SetRhythmNotation), noteRenderer, note, numberedNote)
}
