// Code generated by MockGen. DO NOT EDIT.
// Source: header.go

// Package header is a generated GoMock package.
package header

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	keysig "github.com/jodi-ivan/numbered-notation-xml/internal/keysig"
	musicxml "github.com/jodi-ivan/numbered-notation-xml/internal/musicxml"
	timesig "github.com/jodi-ivan/numbered-notation-xml/internal/timesig"
	repository "github.com/jodi-ivan/numbered-notation-xml/svc/repository"
	canvas "github.com/jodi-ivan/numbered-notation-xml/utils/canvas"
)

// MockHeader is a mock of Header interface.
type MockHeader struct {
	ctrl     *gomock.Controller
	recorder *MockHeaderMockRecorder
}

// MockHeaderMockRecorder is the mock recorder for MockHeader.
type MockHeaderMockRecorder struct {
	mock *MockHeader
}

// NewMockHeader creates a new mock instance.
func NewMockHeader(ctrl *gomock.Controller) *MockHeader {
	mock := &MockHeader{ctrl: ctrl}
	mock.recorder = &MockHeaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHeader) EXPECT() *MockHeaderMockRecorder {
	return m.recorder
}

// RenderKeyandTimeSignatures mocks base method.
func (m *MockHeader) RenderKeyandTimeSignatures(ctx context.Context, canv canvas.Canvas, key keysig.KeySignature, timeSignature timesig.TimeSignature) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderKeyandTimeSignatures", ctx, canv, key, timeSignature)
}

// RenderKeyandTimeSignatures indicates an expected call of RenderKeyandTimeSignatures.
func (mr *MockHeaderMockRecorder) RenderKeyandTimeSignatures(ctx, canv, key, timeSignature interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderKeyandTimeSignatures", reflect.TypeOf((*MockHeader)(nil).RenderKeyandTimeSignatures), ctx, canv, key, timeSignature)
}

// RenderSheetHeader mocks base method.
func (m *MockHeader) RenderSheetHeader(ctx context.Context, canv canvas.Canvas, credit []musicxml.Credit, metadata *repository.HymnMetadata) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderSheetHeader", ctx, canv, credit, metadata)
}

// RenderSheetHeader indicates an expected call of RenderSheetHeader.
func (mr *MockHeaderMockRecorder) RenderSheetHeader(ctx, canv, credit, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderSheetHeader", reflect.TypeOf((*MockHeader)(nil).RenderSheetHeader), ctx, canv, credit, metadata)
}
