// Code generated by MockGen. DO NOT EDIT.
// Source: svc\usecase\usecase.go

// Package mock_usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	canvas "github.com/jodi-ivan/numbered-notation-xml/utils/canvas"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// RenderHymn mocks base method.
func (m *MockUsecase) RenderHymn(ctx context.Context, canv canvas.Canvas, hymnNum int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderHymn", ctx, canv, hymnNum)
	ret0, _ := ret[0].(error)
	return ret0
}

// RenderHymn indicates an expected call of RenderHymn.
func (mr *MockUsecaseMockRecorder) RenderHymn(ctx, canv, hymnNum interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderHymn", reflect.TypeOf((*MockUsecase)(nil).RenderHymn), ctx, canv, hymnNum)
}
