package numbered

const (
	MIN_DISTANCE_BREATH = 10
	Y_OFFSET_BREATH     = 10

	AVERAGE_CHARACTER_WIDTH = 8

	REHERSHAL_CIRCLE_X_OFFSET = 4
	REHERSHAL_CIRCLE_Y_OFFSET = 28
	REHERSHAL_CIRCLE_RADIUS   = 6

	REHERSHAL_TEXT_X_OFFSET = 1
	REHERSHAL_TEXT_Y_OFFSET = 25
)
