// Code generated by MockGen. DO NOT EDIT.
// Source: internal\numbered\numbered.go

// Package numbered is a generated GoMock package.
package numbered

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	timesig "github.com/jodi-ivan/numbered-notation-xml/internal/timesig"
)

// MockNumbered is a mock of Numbered interface.
type MockNumbered struct {
	ctrl     *gomock.Controller
	recorder *MockNumberedMockRecorder
}

// MockNumberedMockRecorder is the mock recorder for MockNumbered.
type MockNumberedMockRecorder struct {
	mock *MockNumbered
}

// NewMockNumbered creates a new mock instance.
func NewMockNumbered(ctrl *gomock.Controller) *MockNumbered {
	mock := &MockNumbered{ctrl: ctrl}
	mock.recorder = &MockNumberedMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNumbered) EXPECT() *MockNumberedMockRecorder {
	return m.recorder
}

// GetLengthNote mocks base method.
func (m *MockNumbered) GetLengthNote(ctx context.Context, ts timesig.TimeSignature, measure int, noteLength float64) []NoteLength {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLengthNote", ctx, ts, measure, noteLength)
	ret0, _ := ret[0].([]NoteLength)
	return ret0
}

// GetLengthNote indicates an expected call of GetLengthNote.
func (mr *MockNumberedMockRecorder) GetLengthNote(ctx, ts, measure, noteLength interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLengthNote", reflect.TypeOf((*MockNumbered)(nil).GetLengthNote), ctx, ts, measure, noteLength)
}
