// Code generated by MockGen. DO NOT EDIT.
// Source: utils\webserver\webserver.go

// Package mock_webserver is a generated GoMock package.
package webserver

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	httprouter "github.com/julienschmidt/httprouter"
)

// MockResponseWriter is a mock of ResponseWriter interface.
type MockResponseWriter struct {
	ctrl     *gomock.Controller
	recorder *MockResponseWriterMockRecorder
}

// MockResponseWriterMockRecorder is the mock recorder for MockResponseWriter.
type MockResponseWriterMockRecorder struct {
	mock *MockResponseWriter
}

// NewMockResponseWriter creates a new mock instance.
func NewMockResponseWriter(ctrl *gomock.Controller) *MockResponseWriter {
	mock := &MockResponseWriter{ctrl: ctrl}
	mock.recorder = &MockResponseWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponseWriter) EXPECT() *MockResponseWriterMockRecorder {
	return m.recorder
}

// Header mocks base method.
func (m *MockResponseWriter) Header() http.Header {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(http.Header)
	return ret0
}

// Header indicates an expected call of Header.
func (mr *MockResponseWriterMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockResponseWriter)(nil).Header))
}

// Write mocks base method.
func (m *MockResponseWriter) Write(data []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", data)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MockResponseWriterMockRecorder) Write(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockResponseWriter)(nil).Write), data)
}

// WriteHeader mocks base method.
func (m *MockResponseWriter) WriteHeader(statusCode int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WriteHeader", statusCode)
}

// WriteHeader indicates an expected call of WriteHeader.
func (mr *MockResponseWriterMockRecorder) WriteHeader(statusCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteHeader", reflect.TypeOf((*MockResponseWriter)(nil).WriteHeader), statusCode)
}

// MockHTTPAdapter is a mock of HTTPAdapter interface.
type MockHTTPAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPAdapterMockRecorder
}

// MockHTTPAdapterMockRecorder is the mock recorder for MockHTTPAdapter.
type MockHTTPAdapterMockRecorder struct {
	mock *MockHTTPAdapter
}

// NewMockHTTPAdapter creates a new mock instance.
func NewMockHTTPAdapter(ctrl *gomock.Controller) *MockHTTPAdapter {
	mock := &MockHTTPAdapter{ctrl: ctrl}
	mock.recorder = &MockHTTPAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPAdapter) EXPECT() *MockHTTPAdapterMockRecorder {
	return m.recorder
}

// ServeHTTP mocks base method.
func (m *MockHTTPAdapter) ServeHTTP(w http.ResponseWriter, r *http.Request, ps httprouter.Params) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServeHTTP", w, r, ps)
}

// ServeHTTP indicates an expected call of ServeHTTP.
func (mr *MockHTTPAdapterMockRecorder) ServeHTTP(w, r, ps interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServeHTTP", reflect.TypeOf((*MockHTTPAdapter)(nil).ServeHTTP), w, r, ps)
}
