// Code generated by MockGen. DO NOT EDIT.
// Source: verse.go

// Package verse is a generated GoMock package.
package verse

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/jodi-ivan/numbered-notation-xml/internal/entity"
	canvas "github.com/jodi-ivan/numbered-notation-xml/utils/canvas"
)

// MockVerse is a mock of Verse interface.
type MockVerse struct {
	ctrl     *gomock.Controller
	recorder *MockVerseMockRecorder
}

// MockVerseMockRecorder is the mock recorder for MockVerse.
type MockVerseMockRecorder struct {
	mock *MockVerse
}

// NewMockVerse creates a new mock instance.
func NewMockVerse(ctrl *gomock.Controller) *MockVerse {
	mock := &MockVerse{ctrl: ctrl}
	mock.recorder = &MockVerseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerse) EXPECT() *MockVerseMockRecorder {
	return m.recorder
}

// RenderVerse mocks base method.
func (m *MockVerse) RenderVerse(ctx context.Context, canv canvas.Canvas, y int, metadata *entity.HymnMetaData) VerseInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderVerse", ctx, canv, y, metadata)
	ret0, _ := ret[0].(VerseInfo)
	return ret0
}

// RenderVerse indicates an expected call of RenderVerse.
func (mr *MockVerseMockRecorder) RenderVerse(ctx, canv, y, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderVerse", reflect.TypeOf((*MockVerse)(nil).RenderVerse), ctx, canv, y, metadata)
}
