// Code generated by MockGen. DO NOT EDIT.
// Source: credits.go

// Package credits is a generated GoMock package.
package credits

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	repository "github.com/jodi-ivan/numbered-notation-xml/svc/repository"
	canvas "github.com/jodi-ivan/numbered-notation-xml/utils/canvas"
)

// MockCredits is a mock of Credits interface.
type MockCredits struct {
	ctrl     *gomock.Controller
	recorder *MockCreditsMockRecorder
}

// MockCreditsMockRecorder is the mock recorder for MockCredits.
type MockCreditsMockRecorder struct {
	mock *MockCredits
}

// NewMockCredits creates a new mock instance.
func NewMockCredits(ctrl *gomock.Controller) *MockCredits {
	mock := &MockCredits{ctrl: ctrl}
	mock.recorder = &MockCreditsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredits) EXPECT() *MockCreditsMockRecorder {
	return m.recorder
}

// RenderCredits mocks base method.
func (m *MockCredits) RenderCredits(ctx context.Context, canv canvas.Canvas, y int, metadata repository.HymnData, verseFootnotes map[int]map[int]repository.VerseFootNotes) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderCredits", ctx, canv, y, metadata, verseFootnotes)
	ret0, _ := ret[0].(int)
	return ret0
}

// RenderCredits indicates an expected call of RenderCredits.
func (mr *MockCreditsMockRecorder) RenderCredits(ctx, canv, y, metadata, verseFootnotes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderCredits", reflect.TypeOf((*MockCredits)(nil).RenderCredits), ctx, canv, y, metadata, verseFootnotes)
}

// RenderForKidsFootnotes mocks base method.
func (m *MockCredits) RenderForKidsFootnotes(ctx context.Context, canv canvas.Canvas, y int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderForKidsFootnotes", ctx, canv, y)
}

// RenderForKidsFootnotes indicates an expected call of RenderForKidsFootnotes.
func (mr *MockCreditsMockRecorder) RenderForKidsFootnotes(ctx, canv, y interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderForKidsFootnotes", reflect.TypeOf((*MockCredits)(nil).RenderForKidsFootnotes), ctx, canv, y)
}
