// Code generated by MockGen. DO NOT EDIT.
// Source: internal\credits\credits.go

// Package credits is a generated GoMock package.
package credits

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	repository "github.com/jodi-ivan/numbered-notation-xml/svc/repository"
	canvas "github.com/jodi-ivan/numbered-notation-xml/utils/canvas"
)

// MockCredits is a mock of Credits interface.
type MockCredits struct {
	ctrl     *gomock.Controller
	recorder *MockCreditsMockRecorder
}

// MockCreditsMockRecorder is the mock recorder for MockCredits.
type MockCreditsMockRecorder struct {
	mock *MockCredits
}

// NewMockCredits creates a new mock instance.
func NewMockCredits(ctrl *gomock.Controller) *MockCredits {
	mock := &MockCredits{ctrl: ctrl}
	mock.recorder = &MockCreditsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredits) EXPECT() *MockCreditsMockRecorder {
	return m.recorder
}

// RenderCredits mocks base method.
func (m *MockCredits) RenderCredits(ctx context.Context, canv canvas.Canvas, y int, metadata repository.HymnData) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderCredits", ctx, canv, y, metadata)
}

// RenderCredits indicates an expected call of RenderCredits.
func (mr *MockCreditsMockRecorder) RenderCredits(ctx, canv, y, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderCredits", reflect.TypeOf((*MockCredits)(nil).RenderCredits), ctx, canv, y, metadata)
}
