// Code generated by MockGen. DO NOT EDIT.
// Source: internal\breathpause\breathpause.go

// Package breathpause is a generated GoMock package.
package breathpause

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/jodi-ivan/numbered-notation-xml/internal/entity"
	musicxml "github.com/jodi-ivan/numbered-notation-xml/internal/musicxml"
)

// MockBreathPause is a mock of BreathPause interface.
type MockBreathPause struct {
	ctrl     *gomock.Controller
	recorder *MockBreathPauseMockRecorder
}

// MockBreathPauseMockRecorder is the mock recorder for MockBreathPause.
type MockBreathPauseMockRecorder struct {
	mock *MockBreathPause
}

// NewMockBreathPause creates a new mock instance.
func NewMockBreathPause(ctrl *gomock.Controller) *MockBreathPause {
	mock := &MockBreathPause{ctrl: ctrl}
	mock.recorder = &MockBreathPauseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBreathPause) EXPECT() *MockBreathPauseMockRecorder {
	return m.recorder
}

// SetAndGetBreathPauseRenderer mocks base method.
func (m *MockBreathPause) SetAndGetBreathPauseRenderer(noteRenderer *entity.NoteRenderer, note musicxml.Note) *entity.NoteRenderer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAndGetBreathPauseRenderer", noteRenderer, note)
	ret0, _ := ret[0].(*entity.NoteRenderer)
	return ret0
}

// SetAndGetBreathPauseRenderer indicates an expected call of SetAndGetBreathPauseRenderer.
func (mr *MockBreathPauseMockRecorder) SetAndGetBreathPauseRenderer(noteRenderer, note interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAndGetBreathPauseRenderer", reflect.TypeOf((*MockBreathPause)(nil).SetAndGetBreathPauseRenderer), noteRenderer, note)
}
