// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: protobuf/hymn.proto

package hymn

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_protobuf_hymn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_hymn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_protobuf_hymn_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinate) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Coordinate) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type RectangularArea struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopLeftPos    *Coordinate            `protobuf:"bytes,1,opt,name=top_left_pos,json=topLeftPos,proto3" json:"top_left_pos,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RectangularArea) Reset() {
	*x = RectangularArea{}
	mi := &file_protobuf_hymn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RectangularArea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RectangularArea) ProtoMessage() {}

func (x *RectangularArea) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_hymn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RectangularArea.ProtoReflect.Descriptor instead.
func (*RectangularArea) Descriptor() ([]byte, []int) {
	return file_protobuf_hymn_proto_rawDescGZIP(), []int{1}
}

func (x *RectangularArea) GetTopLeftPos() *Coordinate {
	if x != nil {
		return x.TopLeftPos
	}
	return nil
}

func (x *RectangularArea) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *RectangularArea) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Step struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DurationMillisecond int32                  `protobuf:"varint,1,opt,name=duration_millisecond,json=durationMillisecond,proto3" json:"duration_millisecond,omitempty"`
	DurationStr         string                 `protobuf:"bytes,2,opt,name=duration_str,json=durationStr,proto3" json:"duration_str,omitempty"`
	LyricPart           int32                  `protobuf:"varint,3,opt,name=lyric_part,json=lyricPart,proto3" json:"lyric_part,omitempty"`
	MeasureNumber       int32                  `protobuf:"varint,4,opt,name=measure_number,json=measureNumber,proto3" json:"measure_number,omitempty"`
	TotalBeat           float64                `protobuf:"fixed64,5,opt,name=total_beat,json=totalBeat,proto3" json:"total_beat,omitempty"`
	Rect                *RectangularArea       `protobuf:"bytes,6,opt,name=rect,proto3" json:"rect,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_protobuf_hymn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_hymn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_protobuf_hymn_proto_rawDescGZIP(), []int{2}
}

func (x *Step) GetDurationMillisecond() int32 {
	if x != nil {
		return x.DurationMillisecond
	}
	return 0
}

func (x *Step) GetDurationStr() string {
	if x != nil {
		return x.DurationStr
	}
	return ""
}

func (x *Step) GetLyricPart() int32 {
	if x != nil {
		return x.LyricPart
	}
	return 0
}

func (x *Step) GetMeasureNumber() int32 {
	if x != nil {
		return x.MeasureNumber
	}
	return 0
}

func (x *Step) GetTotalBeat() float64 {
	if x != nil {
		return x.TotalBeat
	}
	return 0
}

func (x *Step) GetRect() *RectangularArea {
	if x != nil {
		return x.Rect
	}
	return nil
}

type Metadata struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalVerse          int32                  `protobuf:"varint,1,opt,name=total_verse,json=totalVerse,proto3" json:"total_verse,omitempty"`
	Variant             []string               `protobuf:"bytes,2,rep,name=variant,proto3" json:"variant,omitempty"`
	PlaybackStep        []*Step                `protobuf:"bytes,3,rep,name=playback_step,json=playbackStep,proto3" json:"playback_step,omitempty"`
	OverallDurationMill int64                  `protobuf:"varint,4,opt,name=overall_duration_mill,json=overallDurationMill,proto3" json:"overall_duration_mill,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_protobuf_hymn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_hymn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_protobuf_hymn_proto_rawDescGZIP(), []int{3}
}

func (x *Metadata) GetTotalVerse() int32 {
	if x != nil {
		return x.TotalVerse
	}
	return 0
}

func (x *Metadata) GetVariant() []string {
	if x != nil {
		return x.Variant
	}
	return nil
}

func (x *Metadata) GetPlaybackStep() []*Step {
	if x != nil {
		return x.PlaybackStep
	}
	return nil
}

func (x *Metadata) GetOverallDurationMill() int64 {
	if x != nil {
		return x.OverallDurationMill
	}
	return 0
}

type HymnSVG struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	SvgBody       string                 `protobuf:"bytes,2,opt,name=svg_body,json=svgBody,proto3" json:"svg_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HymnSVG) Reset() {
	*x = HymnSVG{}
	mi := &file_protobuf_hymn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HymnSVG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HymnSVG) ProtoMessage() {}

func (x *HymnSVG) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_hymn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HymnSVG.ProtoReflect.Descriptor instead.
func (*HymnSVG) Descriptor() ([]byte, []int) {
	return file_protobuf_hymn_proto_rawDescGZIP(), []int{4}
}

func (x *HymnSVG) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *HymnSVG) GetSvgBody() string {
	if x != nil {
		return x.SvgBody
	}
	return ""
}

var File_protobuf_hymn_proto protoreflect.FileDescriptor

const file_protobuf_hymn_proto_rawDesc = "" +
	"\n" +
	"\x13protobuf/hymn.proto\x12\x04hymn\"(\n" +
	"\n" +
	"Coordinate\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"s\n" +
	"\x0fRectangularArea\x122\n" +
	"\ftop_left_pos\x18\x01 \x01(\v2\x10.hymn.CoordinateR\n" +
	"topLeftPos\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\"\xec\x01\n" +
	"\x04Step\x121\n" +
	"\x14duration_millisecond\x18\x01 \x01(\x05R\x13durationMillisecond\x12!\n" +
	"\fduration_str\x18\x02 \x01(\tR\vdurationStr\x12\x1d\n" +
	"\n" +
	"lyric_part\x18\x03 \x01(\x05R\tlyricPart\x12%\n" +
	"\x0emeasure_number\x18\x04 \x01(\x05R\rmeasureNumber\x12\x1d\n" +
	"\n" +
	"total_beat\x18\x05 \x01(\x01R\ttotalBeat\x12)\n" +
	"\x04rect\x18\x06 \x01(\v2\x15.hymn.RectangularAreaR\x04rect\"\xaa\x01\n" +
	"\bMetadata\x12\x1f\n" +
	"\vtotal_verse\x18\x01 \x01(\x05R\n" +
	"totalVerse\x12\x18\n" +
	"\avariant\x18\x02 \x03(\tR\avariant\x12/\n" +
	"\rplayback_step\x18\x03 \x03(\v2\n" +
	".hymn.StepR\fplaybackStep\x122\n" +
	"\x15overall_duration_mill\x18\x04 \x01(\x03R\x13overallDurationMill\"P\n" +
	"\aHymnSVG\x12*\n" +
	"\bmetadata\x18\x01 \x01(\v2\x0e.hymn.MetadataR\bmetadata\x12\x19\n" +
	"\bsvg_body\x18\x02 \x01(\tR\asvgBodyB:Z8github.com/jodi-ivan/numbered-notation-xml/protobuf/hymnb\x06proto3"

var (
	file_protobuf_hymn_proto_rawDescOnce sync.Once
	file_protobuf_hymn_proto_rawDescData []byte
)

func file_protobuf_hymn_proto_rawDescGZIP() []byte {
	file_protobuf_hymn_proto_rawDescOnce.Do(func() {
		file_protobuf_hymn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_hymn_proto_rawDesc), len(file_protobuf_hymn_proto_rawDesc)))
	})
	return file_protobuf_hymn_proto_rawDescData
}

var file_protobuf_hymn_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protobuf_hymn_proto_goTypes = []any{
	(*Coordinate)(nil),      // 0: hymn.Coordinate
	(*RectangularArea)(nil), // 1: hymn.RectangularArea
	(*Step)(nil),            // 2: hymn.Step
	(*Metadata)(nil),        // 3: hymn.Metadata
	(*HymnSVG)(nil),         // 4: hymn.HymnSVG
}
var file_protobuf_hymn_proto_depIdxs = []int32{
	0, // 0: hymn.RectangularArea.top_left_pos:type_name -> hymn.Coordinate
	1, // 1: hymn.Step.rect:type_name -> hymn.RectangularArea
	2, // 2: hymn.Metadata.playback_step:type_name -> hymn.Step
	3, // 3: hymn.HymnSVG.metadata:type_name -> hymn.Metadata
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protobuf_hymn_proto_init() }
func file_protobuf_hymn_proto_init() {
	if File_protobuf_hymn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_hymn_proto_rawDesc), len(file_protobuf_hymn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_hymn_proto_goTypes,
		DependencyIndexes: file_protobuf_hymn_proto_depIdxs,
		MessageInfos:      file_protobuf_hymn_proto_msgTypes,
	}.Build()
	File_protobuf_hymn_proto = out.File
	file_protobuf_hymn_proto_goTypes = nil
	file_protobuf_hymn_proto_depIdxs = nil
}
