// Code generated by MockGen. DO NOT EDIT.
// Source: gregorian.go

// Package gregorian is a generated GoMock package.
package gregorian

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/jodi-ivan/numbered-notation-xml/internal/entity"
	keysig "github.com/jodi-ivan/numbered-notation-xml/internal/keysig"
	timesig "github.com/jodi-ivan/numbered-notation-xml/internal/timesig"
	canvas "github.com/jodi-ivan/numbered-notation-xml/utils/canvas"
)

// MockGregorian is a mock of Gregorian interface.
type MockGregorian struct {
	ctrl     *gomock.Controller
	recorder *MockGregorianMockRecorder
}

// MockGregorianMockRecorder is the mock recorder for MockGregorian.
type MockGregorianMockRecorder struct {
	mock *MockGregorian
}

// NewMockGregorian creates a new mock instance.
func NewMockGregorian(ctrl *gomock.Controller) *MockGregorian {
	mock := &MockGregorian{ctrl: ctrl}
	mock.recorder = &MockGregorianMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGregorian) EXPECT() *MockGregorianMockRecorder {
	return m.recorder
}

// RenderStaffLine mocks base method.
func (m *MockGregorian) RenderStaffLine(ctx context.Context, staffPos, y int, canv canvas.Canvas, notes []*entity.NoteRenderer, keySignature keysig.KeySignature, timeSignature timesig.TimeSignature) VMargin {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderStaffLine", ctx, staffPos, y, canv, notes, keySignature, timeSignature)
	ret0, _ := ret[0].(VMargin)
	return ret0
}

// RenderStaffLine indicates an expected call of RenderStaffLine.
func (mr *MockGregorianMockRecorder) RenderStaffLine(ctx, staffPos, y, canv, notes, keySignature, timeSignature interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderStaffLine", reflect.TypeOf((*MockGregorian)(nil).RenderStaffLine), ctx, staffPos, y, canv, notes, keySignature, timeSignature)
}
