// Code generated by MockGen. DO NOT EDIT.
// Source: footnote.go

// Package footnote is a generated GoMock package.
package footnote

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/jodi-ivan/numbered-notation-xml/internal/entity"
	repository "github.com/jodi-ivan/numbered-notation-xml/svc/repository"
	canvas "github.com/jodi-ivan/numbered-notation-xml/utils/canvas"
)

// MockFootnote is a mock of Footnote interface.
type MockFootnote struct {
	ctrl     *gomock.Controller
	recorder *MockFootnoteMockRecorder
}

// MockFootnoteMockRecorder is the mock recorder for MockFootnote.
type MockFootnoteMockRecorder struct {
	mock *MockFootnote
}

// NewMockFootnote creates a new mock instance.
func NewMockFootnote(ctrl *gomock.Controller) *MockFootnote {
	mock := &MockFootnote{ctrl: ctrl}
	mock.recorder = &MockFootnoteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFootnote) EXPECT() *MockFootnoteMockRecorder {
	return m.recorder
}

// AssignFootnotesMarker mocks base method.
func (m *MockFootnote) AssignFootnotesMarker(canv canvas.Canvas, pos entity.Coordinate, defaultX int, cursor VerseLineCursor, verseFootnote map[int]map[int]repository.VerseFootNotes) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AssignFootnotesMarker", canv, pos, defaultX, cursor, verseFootnote)
}

// AssignFootnotesMarker indicates an expected call of AssignFootnotesMarker.
func (mr *MockFootnoteMockRecorder) AssignFootnotesMarker(canv, pos, defaultX, cursor, verseFootnote interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignFootnotesMarker", reflect.TypeOf((*MockFootnote)(nil).AssignFootnotesMarker), canv, pos, defaultX, cursor, verseFootnote)
}

// RenderMusicFootnotes mocks base method.
func (m *MockFootnote) RenderMusicFootnotes(ctx context.Context, canv canvas.Canvas, metadata *repository.HymnMetadata, y int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderMusicFootnotes", ctx, canv, metadata, y)
}

// RenderMusicFootnotes indicates an expected call of RenderMusicFootnotes.
func (mr *MockFootnoteMockRecorder) RenderMusicFootnotes(ctx, canv, metadata, y interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderMusicFootnotes", reflect.TypeOf((*MockFootnote)(nil).RenderMusicFootnotes), ctx, canv, metadata, y)
}

// RenderTitleFootnotes mocks base method.
func (m *MockFootnote) RenderTitleFootnotes(canv canvas.Canvas, y int, metadata repository.HymnData) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderTitleFootnotes", canv, y, metadata)
}

// RenderTitleFootnotes indicates an expected call of RenderTitleFootnotes.
func (mr *MockFootnoteMockRecorder) RenderTitleFootnotes(canv, y, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderTitleFootnotes", reflect.TypeOf((*MockFootnote)(nil).RenderTitleFootnotes), canv, y, metadata)
}

// RenderVerseFootnotes mocks base method.
func (m *MockFootnote) RenderVerseFootnotes(canv canvas.Canvas, y *int, footnotes map[int]map[int]repository.VerseFootNotes) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderVerseFootnotes", canv, y, footnotes)
}

// RenderVerseFootnotes indicates an expected call of RenderVerseFootnotes.
func (mr *MockFootnoteMockRecorder) RenderVerseFootnotes(canv, y, footnotes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderVerseFootnotes", reflect.TypeOf((*MockFootnote)(nil).RenderVerseFootnotes), canv, y, footnotes)
}
