// Code generated by MockGen. DO NOT EDIT.
// Source: internal\staff\align.go

// Package staff is a generated GoMock package.
package staff

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/jodi-ivan/numbered-notation-xml/internal/entity"
	canvas "github.com/jodi-ivan/numbered-notation-xml/utils/canvas"
)

// MockRenderStaffWithAlign is a mock of RenderStaffWithAlign interface.
type MockRenderStaffWithAlign struct {
	ctrl     *gomock.Controller
	recorder *MockRenderStaffWithAlignMockRecorder
}

// MockRenderStaffWithAlignMockRecorder is the mock recorder for MockRenderStaffWithAlign.
type MockRenderStaffWithAlignMockRecorder struct {
	mock *MockRenderStaffWithAlign
}

// NewMockRenderStaffWithAlign creates a new mock instance.
func NewMockRenderStaffWithAlign(ctrl *gomock.Controller) *MockRenderStaffWithAlign {
	mock := &MockRenderStaffWithAlign{ctrl: ctrl}
	mock.recorder = &MockRenderStaffWithAlignMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRenderStaffWithAlign) EXPECT() *MockRenderStaffWithAlignMockRecorder {
	return m.recorder
}

// RenderWithAlign mocks base method.
func (m *MockRenderStaffWithAlign) RenderWithAlign(ctx context.Context, canv canvas.Canvas, y int, noteRenderer [][]*entity.NoteRenderer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderWithAlign", ctx, canv, y, noteRenderer)
}

// RenderWithAlign indicates an expected call of RenderWithAlign.
func (mr *MockRenderStaffWithAlignMockRecorder) RenderWithAlign(ctx, canv, y, noteRenderer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderWithAlign", reflect.TypeOf((*MockRenderStaffWithAlign)(nil).RenderWithAlign), ctx, canv, y, noteRenderer)
}
