// Code generated by MockGen. DO NOT EDIT.
// Source: internal\staff\staff.go

// Package staff is a generated GoMock package.
package staff

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/jodi-ivan/numbered-notation-xml/internal/entity"
	keysig "github.com/jodi-ivan/numbered-notation-xml/internal/keysig"
	musicxml "github.com/jodi-ivan/numbered-notation-xml/internal/musicxml"
	timesig "github.com/jodi-ivan/numbered-notation-xml/internal/timesig"
	canvas "github.com/jodi-ivan/numbered-notation-xml/utils/canvas"
)

// MockStaff is a mock of Staff interface.
type MockStaff struct {
	ctrl     *gomock.Controller
	recorder *MockStaffMockRecorder
}

// MockStaffMockRecorder is the mock recorder for MockStaff.
type MockStaffMockRecorder struct {
	mock *MockStaff
}

// NewMockStaff creates a new mock instance.
func NewMockStaff(ctrl *gomock.Controller) *MockStaff {
	mock := &MockStaff{ctrl: ctrl}
	mock.recorder = &MockStaffMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStaff) EXPECT() *MockStaffMockRecorder {
	return m.recorder
}

// RenderStaff mocks base method.
func (m *MockStaff) RenderStaff(ctx context.Context, canv canvas.Canvas, x, y int, keySignature keysig.KeySignature, timeSignature timesig.TimeSignature, measures []musicxml.Measure, prevNotes ...*entity.NoteRenderer) StaffInfo {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, canv, x, y, keySignature, timeSignature, measures}
	for _, a := range prevNotes {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RenderStaff", varargs...)
	ret0, _ := ret[0].(StaffInfo)
	return ret0
}

// RenderStaff indicates an expected call of RenderStaff.
func (mr *MockStaffMockRecorder) RenderStaff(ctx, canv, x, y, keySignature, timeSignature, measures interface{}, prevNotes ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, canv, x, y, keySignature, timeSignature, measures}, prevNotes...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderStaff", reflect.TypeOf((*MockStaff)(nil).RenderStaff), varargs...)
}

// SplitLines mocks base method.
func (m *MockStaff) SplitLines(ctx context.Context, part musicxml.Part) [][]musicxml.Measure {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SplitLines", ctx, part)
	ret0, _ := ret[0].([][]musicxml.Measure)
	return ret0
}

// SplitLines indicates an expected call of SplitLines.
func (mr *MockStaffMockRecorder) SplitLines(ctx, part interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SplitLines", reflect.TypeOf((*MockStaff)(nil).SplitLines), ctx, part)
}
