// Code generated by MockGen. DO NOT EDIT.
// Source: staff.go

// Package staff is a generated GoMock package.
package staff

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/jodi-ivan/numbered-notation-xml/internal/entity"
	keysig "github.com/jodi-ivan/numbered-notation-xml/internal/keysig"
	musicxml "github.com/jodi-ivan/numbered-notation-xml/internal/musicxml"
	timesig "github.com/jodi-ivan/numbered-notation-xml/internal/timesig"
	repository "github.com/jodi-ivan/numbered-notation-xml/svc/repository"
	canvas "github.com/jodi-ivan/numbered-notation-xml/utils/canvas"
)

// MockStaff is a mock of Staff interface.
type MockStaff struct {
	ctrl     *gomock.Controller
	recorder *MockStaffMockRecorder
}

// MockStaffMockRecorder is the mock recorder for MockStaff.
type MockStaffMockRecorder struct {
	mock *MockStaff
}

// NewMockStaff creates a new mock instance.
func NewMockStaff(ctrl *gomock.Controller) *MockStaff {
	mock := &MockStaff{ctrl: ctrl}
	mock.recorder = &MockStaffMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStaff) EXPECT() *MockStaffMockRecorder {
	return m.recorder
}

// Render mocks base method.
func (m *MockStaff) Render(ctx context.Context, canv canvas.Canvas, part musicxml.Part, keySignature keysig.KeySignature, timeSignature timesig.TimeSignature, metadata *repository.HymnMetadata) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", ctx, canv, part, keySignature, timeSignature, metadata)
	ret0, _ := ret[0].(int)
	return ret0
}

// Render indicates an expected call of Render.
func (mr *MockStaffMockRecorder) Render(ctx, canv, part, keySignature, timeSignature, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockStaff)(nil).Render), ctx, canv, part, keySignature, timeSignature, metadata)
}

// RenderStaff mocks base method.
func (m *MockStaff) RenderStaff(ctx context.Context, canv canvas.Canvas, x, y int, metadata *repository.HymnMetadata, measures []musicxml.Measure, data StaffData) StaffInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderStaff", ctx, canv, x, y, metadata, measures, data)
	ret0, _ := ret[0].(StaffInfo)
	return ret0
}

// RenderStaff indicates an expected call of RenderStaff.
func (mr *MockStaffMockRecorder) RenderStaff(ctx, canv, x, y, metadata, measures, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderStaff", reflect.TypeOf((*MockStaff)(nil).RenderStaff), ctx, canv, x, y, metadata, measures, data)
}

// SetMeasureTextRenderer mocks base method.
func (m *MockStaff) SetMeasureTextRenderer(noteRenderer *entity.NoteRenderer, note musicxml.Note, directionDashses map[int]musicxml.DirectionDashesType, isLastNote bool) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMeasureTextRenderer", noteRenderer, note, directionDashses, isLastNote)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SetMeasureTextRenderer indicates an expected call of SetMeasureTextRenderer.
func (mr *MockStaffMockRecorder) SetMeasureTextRenderer(noteRenderer, note, directionDashses, isLastNote interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMeasureTextRenderer", reflect.TypeOf((*MockStaff)(nil).SetMeasureTextRenderer), noteRenderer, note, directionDashses, isLastNote)
}

// SplitLines mocks base method.
func (m *MockStaff) SplitLines(ctx context.Context, part musicxml.Part) [][]musicxml.Measure {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SplitLines", ctx, part)
	ret0, _ := ret[0].([][]musicxml.Measure)
	return ret0
}

// SplitLines indicates an expected call of SplitLines.
func (mr *MockStaffMockRecorder) SplitLines(ctx, part interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SplitLines", reflect.TypeOf((*MockStaff)(nil).SplitLines), ctx, part)
}
