// Code generated by MockGen. DO NOT EDIT.
// Source: splitter.go

// Package splitter is a generated GoMock package.
package splitter

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/jodi-ivan/numbered-notation-xml/internal/entity"
	timesig "github.com/jodi-ivan/numbered-notation-xml/internal/timesig"
)

// MockBeamSplitter is a mock of BeamSplitter interface.
type MockBeamSplitter struct {
	ctrl     *gomock.Controller
	recorder *MockBeamSplitterMockRecorder
}

// MockBeamSplitterMockRecorder is the mock recorder for MockBeamSplitter.
type MockBeamSplitterMockRecorder struct {
	mock *MockBeamSplitter
}

// NewMockBeamSplitter creates a new mock instance.
func NewMockBeamSplitter(ctrl *gomock.Controller) *MockBeamSplitter {
	mock := &MockBeamSplitter{ctrl: ctrl}
	mock.recorder = &MockBeamSplitterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBeamSplitter) EXPECT() *MockBeamSplitterMockRecorder {
	return m.recorder
}

// Split mocks base method.
func (m *MockBeamSplitter) Split(ctx context.Context, notes []*entity.NoteRenderer, ts timesig.TimeSignature, segments map[int][]BeamSplitMarker) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Split", ctx, notes, ts, segments)
}

// Split indicates an expected call of Split.
func (mr *MockBeamSplitterMockRecorder) Split(ctx, notes, ts, segments interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Split", reflect.TypeOf((*MockBeamSplitter)(nil).Split), ctx, notes, ts, segments)
}

// SplitSingle mocks base method.
func (m *MockBeamSplitter) SplitSingle(ctx context.Context, notes []*entity.NoteRenderer, ts timesig.TimeSignature, segments []BeamSplitMarker, beamNo int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SplitSingle", ctx, notes, ts, segments, beamNo)
}

// SplitSingle indicates an expected call of SplitSingle.
func (mr *MockBeamSplitterMockRecorder) SplitSingle(ctx, notes, ts, segments, beamNo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SplitSingle", reflect.TypeOf((*MockBeamSplitter)(nil).SplitSingle), ctx, notes, ts, segments, beamNo)
}
