// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package toping

import (
	"context"

	"github.com/jodi-ivan/numbered-notation-xml/internal/entity"
	"github.com/jodi-ivan/numbered-notation-xml/internal/musicxml"
	"github.com/jodi-ivan/numbered-notation-xml/internal/staff/lines"
	"github.com/jodi-ivan/numbered-notation-xml/utils/canvas"
	mock "github.com/stretchr/testify/mock"
)

// NewMockToping creates a new instance of MockToping. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToping(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToping {
	mock := &MockToping{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockToping is an autogenerated mock type for the Toping type
type MockToping struct {
	mock.Mock
}

type MockToping_Expecter struct {
	mock *mock.Mock
}

func (_m *MockToping) EXPECT() *MockToping_Expecter {
	return &MockToping_Expecter{mock: &_m.Mock}
}

// RenderRepeatMeasure provides a mock function for the type MockToping
func (_mock *MockToping) RenderRepeatMeasure(ctx context.Context, y int, canv canvas.Canvas, notes []*entity.NoteRenderer, std ...bool) {
	if len(std) > 0 {
		_mock.Called(ctx, y, canv, notes, std)
	} else {
		_mock.Called(ctx, y, canv, notes)
	}

	return
}

// MockToping_RenderRepeatMeasure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderRepeatMeasure'
type MockToping_RenderRepeatMeasure_Call struct {
	*mock.Call
}

// RenderRepeatMeasure is a helper method to define mock.On call
//   - ctx context.Context
//   - y int
//   - canv canvas.Canvas
//   - notes []*entity.NoteRenderer
//   - std ...bool
func (_e *MockToping_Expecter) RenderRepeatMeasure(ctx interface{}, y interface{}, canv interface{}, notes interface{}, std ...interface{}) *MockToping_RenderRepeatMeasure_Call {
	return &MockToping_RenderRepeatMeasure_Call{Call: _e.mock.On("RenderRepeatMeasure",
		append([]interface{}{ctx, y, canv, notes}, std...)...)}
}

func (_c *MockToping_RenderRepeatMeasure_Call) Run(run func(ctx context.Context, y int, canv canvas.Canvas, notes []*entity.NoteRenderer, std ...bool)) *MockToping_RenderRepeatMeasure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 canvas.Canvas
		if args[2] != nil {
			arg2 = args[2].(canvas.Canvas)
		}
		var arg3 []*entity.NoteRenderer
		if args[3] != nil {
			arg3 = args[3].([]*entity.NoteRenderer)
		}
		var arg4 []bool
		var variadicArgs []bool
		if len(args) > 4 {
			variadicArgs = args[4].([]bool)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockToping_RenderRepeatMeasure_Call) Return() *MockToping_RenderRepeatMeasure_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockToping_RenderRepeatMeasure_Call) RunAndReturn(run func(ctx context.Context, y int, canv canvas.Canvas, notes []*entity.NoteRenderer, std ...bool)) *MockToping_RenderRepeatMeasure_Call {
	_c.Run(run)
	return _c
}

// RenderStaffLineDash provides a mock function for the type MockToping
func (_mock *MockToping) RenderStaffLineDash(notes []*entity.NoteRenderer, canv canvas.Canvas, y int, linestaff ...lines.LineStaff) {
	if len(linestaff) > 0 {
		_mock.Called(notes, canv, y, linestaff)
	} else {
		_mock.Called(notes, canv, y)
	}

	return
}

// MockToping_RenderStaffLineDash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderStaffLineDash'
type MockToping_RenderStaffLineDash_Call struct {
	*mock.Call
}

// RenderStaffLineDash is a helper method to define mock.On call
//   - notes []*entity.NoteRenderer
//   - canv canvas.Canvas
//   - y int
//   - linestaff ...lines.LineStaff
func (_e *MockToping_Expecter) RenderStaffLineDash(notes interface{}, canv interface{}, y interface{}, linestaff ...interface{}) *MockToping_RenderStaffLineDash_Call {
	return &MockToping_RenderStaffLineDash_Call{Call: _e.mock.On("RenderStaffLineDash",
		append([]interface{}{notes, canv, y}, linestaff...)...)}
}

func (_c *MockToping_RenderStaffLineDash_Call) Run(run func(notes []*entity.NoteRenderer, canv canvas.Canvas, y int, linestaff ...lines.LineStaff)) *MockToping_RenderStaffLineDash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*entity.NoteRenderer
		if args[0] != nil {
			arg0 = args[0].([]*entity.NoteRenderer)
		}
		var arg1 canvas.Canvas
		if args[1] != nil {
			arg1 = args[1].(canvas.Canvas)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 []lines.LineStaff
		var variadicArgs []lines.LineStaff
		if len(args) > 3 {
			variadicArgs = args[3].([]lines.LineStaff)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockToping_RenderStaffLineDash_Call) Return() *MockToping_RenderStaffLineDash_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockToping_RenderStaffLineDash_Call) RunAndReturn(run func(notes []*entity.NoteRenderer, canv canvas.Canvas, y int, linestaff ...lines.LineStaff)) *MockToping_RenderStaffLineDash_Call {
	_c.Run(run)
	return _c
}

// RenderTuplet provides a mock function for the type MockToping
func (_mock *MockToping) RenderTuplet(ctx context.Context, y int, canv canvas.Canvas, notes []*entity.NoteRenderer) {
	_mock.Called(ctx, y, canv, notes)
	return
}

// MockToping_RenderTuplet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderTuplet'
type MockToping_RenderTuplet_Call struct {
	*mock.Call
}

// RenderTuplet is a helper method to define mock.On call
//   - ctx context.Context
//   - y int
//   - canv canvas.Canvas
//   - notes []*entity.NoteRenderer
func (_e *MockToping_Expecter) RenderTuplet(ctx interface{}, y interface{}, canv interface{}, notes interface{}) *MockToping_RenderTuplet_Call {
	return &MockToping_RenderTuplet_Call{Call: _e.mock.On("RenderTuplet", ctx, y, canv, notes)}
}

func (_c *MockToping_RenderTuplet_Call) Run(run func(ctx context.Context, y int, canv canvas.Canvas, notes []*entity.NoteRenderer)) *MockToping_RenderTuplet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 canvas.Canvas
		if args[2] != nil {
			arg2 = args[2].(canvas.Canvas)
		}
		var arg3 []*entity.NoteRenderer
		if args[3] != nil {
			arg3 = args[3].([]*entity.NoteRenderer)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockToping_RenderTuplet_Call) Return() *MockToping_RenderTuplet_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockToping_RenderTuplet_Call) RunAndReturn(run func(ctx context.Context, y int, canv canvas.Canvas, notes []*entity.NoteRenderer)) *MockToping_RenderTuplet_Call {
	_c.Run(run)
	return _c
}

// SetStaffLineDashRenderer provides a mock function for the type MockToping
func (_mock *MockToping) SetStaffLineDashRenderer(note *entity.NoteRenderer, dashes map[int]musicxml.DirectionDashesType) {
	_mock.Called(note, dashes)
	return
}

// MockToping_SetStaffLineDashRenderer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStaffLineDashRenderer'
type MockToping_SetStaffLineDashRenderer_Call struct {
	*mock.Call
}

// SetStaffLineDashRenderer is a helper method to define mock.On call
//   - note *entity.NoteRenderer
//   - dashes map[int]musicxml.DirectionDashesType
func (_e *MockToping_Expecter) SetStaffLineDashRenderer(note interface{}, dashes interface{}) *MockToping_SetStaffLineDashRenderer_Call {
	return &MockToping_SetStaffLineDashRenderer_Call{Call: _e.mock.On("SetStaffLineDashRenderer", note, dashes)}
}

func (_c *MockToping_SetStaffLineDashRenderer_Call) Run(run func(note *entity.NoteRenderer, dashes map[int]musicxml.DirectionDashesType)) *MockToping_SetStaffLineDashRenderer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.NoteRenderer
		if args[0] != nil {
			arg0 = args[0].(*entity.NoteRenderer)
		}
		var arg1 map[int]musicxml.DirectionDashesType
		if args[1] != nil {
			arg1 = args[1].(map[int]musicxml.DirectionDashesType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockToping_SetStaffLineDashRenderer_Call) Return() *MockToping_SetStaffLineDashRenderer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockToping_SetStaffLineDashRenderer_Call) RunAndReturn(run func(note *entity.NoteRenderer, dashes map[int]musicxml.DirectionDashesType)) *MockToping_SetStaffLineDashRenderer_Call {
	_c.Run(run)
	return _c
}
