package canvas

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"strings"

	svg "github.com/ajstarks/svgo"
)

type BufferedCanvas struct {
	s          *_canvas
	d          Delegator
	Width      int
	Height     int
	ns         []string
	bodyBuffer *bytes.Buffer
	finalBuff  io.Writer
}

func (c *BufferedCanvas) Start(w int, h int, ns ...string) {
	c.Width = w
	c.Height = h
	c.ns = []string{`xmlns="http://www.w3.org/2000/svg"`, `xmlns:xlink="http://www.w3.org/1999/xlink"`}
	c.ns = append(c.ns, ns...)

}
func (c *BufferedCanvas) End() {
	c.s.End()
	// c.d.OnBeforeStartWrite()

	if writer, ok := c.s.Writer().(*bufio.Writer); ok {
		writer.Flush()
	}

	svgtop := `<?xml version="1.0"?>
	<!-- Generated by SVGo -->
	<svg width="%d" height="%d" %s>`
	head := fmt.Sprintf(svgtop, c.Width, c.Height, strings.Join(c.ns, " "))

	// Step A: Write the correct dynamic header downstream
	_, err := io.WriteString(c.finalBuff, head)
	if err != nil {
		c.d.OnError(err)
		return
	}

	// Step B: Write the complete, un-truncated music/verse data layout right behind it
	_, err = c.finalBuff.Write(c.bodyBuffer.Bytes())
	if err != nil {
		c.d.OnError(err)
		return
	}
}
func (c *BufferedCanvas) Def() {
	c.s.Def()
}
func (c *BufferedCanvas) DefEnd() {
	c.s.DefEnd()
}
func (c *BufferedCanvas) Group(s ...string) {
	c.s.Group(s...)
}
func (c *BufferedCanvas) Gend() {
	c.s.Gend()
}
func (c *BufferedCanvas) Circle(x int, y int, r int, s ...string) {
	c.s.Circle(x, y, r, s...)
}
func (c *BufferedCanvas) Line(x1 int, y1 int, x2 int, y2 int, s ...string) {
	c.s.Line(x1, y1, x2, y2, s...)
}

func (c *BufferedCanvas) Path(d string, s ...string) {
	c.s.Path(d, s...)
}
func (c *BufferedCanvas) Qbez(sx int, sy int, cx int, cy int, ex int, ey int, s ...string) {
	c.s.Qbez(sx, sy, cx, cy, ex, ey, s...)
}
func (c *BufferedCanvas) Qbezier(sx int, sy int, cx int, cy int, ex int, ey int, tx int, ty int, s ...string) {
	c.s.Qbezier(sx, sy, cx, cy, ex, ey, tx, ty, s...)
}
func (c *BufferedCanvas) Text(x int, y int, t string, s ...string) {
	c.s.Text(x, y, t, s...)
}

func (c *BufferedCanvas) Rect(x int, y int, w int, h int, s ...string) {
	c.s.Rect(x, y, w, h, s...)
}
func (c *BufferedCanvas) CenterRect(x int, y int, w int, h int, s ...string) {
	c.s.CenterRect(x, y, w, h, s...)
}

func (c *BufferedCanvas) Writer() io.Writer {
	return c.s.Writer()
}

func (c *BufferedCanvas) Delegator() Delegator {
	if c.d == nil {
		return &delegatorDiscard{}
	}
	return c.d
}

func (c *BufferedCanvas) TextUnescaped(x float64, y float64, t string, s ...string) {
	c.s.TextUnescaped(x, y, t, s...)

}

func (c *BufferedCanvas) LineFloat64(x1, y1, x2, y2 float64, s ...string) {
	c.s.LineFloat64(x1, y1, x2, y2, s...)
}

func NewBufferedCanvas(buff io.Writer, d Delegator) Canvas {
	var bodyBuffer bytes.Buffer

	return &BufferedCanvas{
		// SVGo writes into our temporary isolated body block
		s:          &_canvas{s: svg.New(&bodyBuffer)},
		d:          d,
		bodyBuffer: &bodyBuffer,
		finalBuff:  buff, // Store the abstract io.Writer string/file/http stream
	}
}
