// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package canvas

import (
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDelegator creates a new instance of MockDelegator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDelegatorTestify(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDelegatorTestify {
	mock := &MockDelegatorTestify{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDelegatorTestify is an autogenerated mock type for the Delegator type
type MockDelegatorTestify struct {
	mock.Mock
}

type MockDelegator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDelegatorTestify) EXPECT() *MockDelegator_Expecter {
	return &MockDelegator_Expecter{mock: &_m.Mock}
}

// OnBeforeStartWrite provides a mock function for the type MockDelegatorTestify
func (_mock *MockDelegatorTestify) OnBeforeStartWrite() {
	_mock.Called()
	return
}

// MockDelegator_OnBeforeStartWrite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnBeforeStartWrite'
type MockDelegator_OnBeforeStartWrite_Call struct {
	*mock.Call
}

// OnBeforeStartWrite is a helper method to define mock.On call
func (_e *MockDelegator_Expecter) OnBeforeStartWrite() *MockDelegator_OnBeforeStartWrite_Call {
	return &MockDelegator_OnBeforeStartWrite_Call{Call: _e.mock.On("OnBeforeStartWrite")}
}

func (_c *MockDelegator_OnBeforeStartWrite_Call) Run(run func()) *MockDelegator_OnBeforeStartWrite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDelegator_OnBeforeStartWrite_Call) Return() *MockDelegator_OnBeforeStartWrite_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDelegator_OnBeforeStartWrite_Call) RunAndReturn(run func()) *MockDelegator_OnBeforeStartWrite_Call {
	_c.Run(run)
	return _c
}

// OnError provides a mock function for the type MockDelegatorTestify
func (_mock *MockDelegatorTestify) OnError(err error) DelegatorErrorFlowControl {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for OnError")
	}

	var r0 DelegatorErrorFlowControl
	if returnFunc, ok := ret.Get(0).(func(error) DelegatorErrorFlowControl); ok {
		r0 = returnFunc(err)
	} else {
		r0 = ret.Get(0).(DelegatorErrorFlowControl)
	}
	return r0
}

// MockDelegator_OnError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnError'
type MockDelegator_OnError_Call struct {
	*mock.Call
}

// OnError is a helper method to define mock.On call
//   - err error
func (_e *MockDelegator_Expecter) OnError(err interface{}) *MockDelegator_OnError_Call {
	return &MockDelegator_OnError_Call{Call: _e.mock.On("OnError", err)}
}

func (_c *MockDelegator_OnError_Call) Run(run func(err error)) *MockDelegator_OnError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDelegator_OnError_Call) Return(delegatorErrorFlowControl DelegatorErrorFlowControl) *MockDelegator_OnError_Call {
	_c.Call.Return(delegatorErrorFlowControl)
	return _c
}

func (_c *MockDelegator_OnError_Call) RunAndReturn(run func(err error) DelegatorErrorFlowControl) *MockDelegator_OnError_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCanvas creates a new instance of MockCanvasTestify. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCanvasTestify(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCanvasTestify {
	mock := &MockCanvasTestify{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCanvasTestify is an autogenerated mock type for the Canvas type
type MockCanvasTestify struct {
	mock.Mock
}

type MockCanvas_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCanvasTestify) EXPECT() *MockCanvas_Expecter {
	return &MockCanvas_Expecter{mock: &_m.Mock}
}

// CenterRect provides a mock function for the type MockCanvasTestify
func (_mock *MockCanvasTestify) CenterRect(x int, y int, w int, h int, s ...string) {
	if len(s) > 0 {
		_mock.Called(x, y, w, h, s)
	} else {
		_mock.Called(x, y, w, h)
	}

	return
}

// MockCanvas_CenterRect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CenterRect'
type MockCanvas_CenterRect_Call struct {
	*mock.Call
}

// CenterRect is a helper method to define mock.On call
//   - x int
//   - y int
//   - w int
//   - h int
//   - s ...string
func (_e *MockCanvas_Expecter) CenterRect(x interface{}, y interface{}, w interface{}, h interface{}, s ...interface{}) *MockCanvas_CenterRect_Call {
	return &MockCanvas_CenterRect_Call{Call: _e.mock.On("CenterRect",
		append([]interface{}{x, y, w, h}, s...)...)}
}

func (_c *MockCanvas_CenterRect_Call) Run(run func(x int, y int, w int, h int, s ...string)) *MockCanvas_CenterRect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 []string
		var variadicArgs []string
		if len(args) > 4 {
			variadicArgs = args[4].([]string)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockCanvas_CenterRect_Call) Return() *MockCanvas_CenterRect_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCanvas_CenterRect_Call) RunAndReturn(run func(x int, y int, w int, h int, s ...string)) *MockCanvas_CenterRect_Call {
	_c.Run(run)
	return _c
}

// Circle provides a mock function for the type MockCanvasTestify
func (_mock *MockCanvasTestify) Circle(x int, y int, r int, s ...string) {
	if len(s) > 0 {
		_mock.Called(x, y, r, s)
	} else {
		_mock.Called(x, y, r)
	}

	return
}

// MockCanvas_Circle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Circle'
type MockCanvas_Circle_Call struct {
	*mock.Call
}

// Circle is a helper method to define mock.On call
//   - x int
//   - y int
//   - r int
//   - s ...string
func (_e *MockCanvas_Expecter) Circle(x interface{}, y interface{}, r interface{}, s ...interface{}) *MockCanvas_Circle_Call {
	return &MockCanvas_Circle_Call{Call: _e.mock.On("Circle",
		append([]interface{}{x, y, r}, s...)...)}
}

func (_c *MockCanvas_Circle_Call) Run(run func(x int, y int, r int, s ...string)) *MockCanvas_Circle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 []string
		var variadicArgs []string
		if len(args) > 3 {
			variadicArgs = args[3].([]string)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockCanvas_Circle_Call) Return() *MockCanvas_Circle_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCanvas_Circle_Call) RunAndReturn(run func(x int, y int, r int, s ...string)) *MockCanvas_Circle_Call {
	_c.Run(run)
	return _c
}

// Def provides a mock function for the type MockCanvasTestify
func (_mock *MockCanvasTestify) Def() {
	_mock.Called()
	return
}

// MockCanvas_Def_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Def'
type MockCanvas_Def_Call struct {
	*mock.Call
}

// Def is a helper method to define mock.On call
func (_e *MockCanvas_Expecter) Def() *MockCanvas_Def_Call {
	return &MockCanvas_Def_Call{Call: _e.mock.On("Def")}
}

func (_c *MockCanvas_Def_Call) Run(run func()) *MockCanvas_Def_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCanvas_Def_Call) Return() *MockCanvas_Def_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCanvas_Def_Call) RunAndReturn(run func()) *MockCanvas_Def_Call {
	_c.Run(run)
	return _c
}

// DefEnd provides a mock function for the type MockCanvasTestify
func (_mock *MockCanvasTestify) DefEnd() {
	_mock.Called()
	return
}

// MockCanvas_DefEnd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefEnd'
type MockCanvas_DefEnd_Call struct {
	*mock.Call
}

// DefEnd is a helper method to define mock.On call
func (_e *MockCanvas_Expecter) DefEnd() *MockCanvas_DefEnd_Call {
	return &MockCanvas_DefEnd_Call{Call: _e.mock.On("DefEnd")}
}

func (_c *MockCanvas_DefEnd_Call) Run(run func()) *MockCanvas_DefEnd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCanvas_DefEnd_Call) Return() *MockCanvas_DefEnd_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCanvas_DefEnd_Call) RunAndReturn(run func()) *MockCanvas_DefEnd_Call {
	_c.Run(run)
	return _c
}

// Delegator provides a mock function for the type MockCanvasTestify
func (_mock *MockCanvasTestify) Delegator() Delegator {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Delegator")
	}

	var r0 Delegator
	if returnFunc, ok := ret.Get(0).(func() Delegator); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Delegator)
		}
	}
	return r0
}

// MockCanvas_Delegator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delegator'
type MockCanvas_Delegator_Call struct {
	*mock.Call
}

// Delegator is a helper method to define mock.On call
func (_e *MockCanvas_Expecter) Delegator() *MockCanvas_Delegator_Call {
	return &MockCanvas_Delegator_Call{Call: _e.mock.On("Delegator")}
}

func (_c *MockCanvas_Delegator_Call) Run(run func()) *MockCanvas_Delegator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCanvas_Delegator_Call) Return(delegator Delegator) *MockCanvas_Delegator_Call {
	_c.Call.Return(delegator)
	return _c
}

func (_c *MockCanvas_Delegator_Call) RunAndReturn(run func() Delegator) *MockCanvas_Delegator_Call {
	_c.Call.Return(run)
	return _c
}

// End provides a mock function for the type MockCanvasTestify
func (_mock *MockCanvasTestify) End() {
	_mock.Called()
	return
}

// MockCanvas_End_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'End'
type MockCanvas_End_Call struct {
	*mock.Call
}

// End is a helper method to define mock.On call
func (_e *MockCanvas_Expecter) End() *MockCanvas_End_Call {
	return &MockCanvas_End_Call{Call: _e.mock.On("End")}
}

func (_c *MockCanvas_End_Call) Run(run func()) *MockCanvas_End_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCanvas_End_Call) Return() *MockCanvas_End_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCanvas_End_Call) RunAndReturn(run func()) *MockCanvas_End_Call {
	_c.Run(run)
	return _c
}

// Gend provides a mock function for the type MockCanvasTestify
func (_mock *MockCanvasTestify) Gend() {
	_mock.Called()
	return
}

// MockCanvas_Gend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Gend'
type MockCanvas_Gend_Call struct {
	*mock.Call
}

// Gend is a helper method to define mock.On call
func (_e *MockCanvas_Expecter) Gend() *MockCanvas_Gend_Call {
	return &MockCanvas_Gend_Call{Call: _e.mock.On("Gend")}
}

func (_c *MockCanvas_Gend_Call) Run(run func()) *MockCanvas_Gend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCanvas_Gend_Call) Return() *MockCanvas_Gend_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCanvas_Gend_Call) RunAndReturn(run func()) *MockCanvas_Gend_Call {
	_c.Run(run)
	return _c
}

// Group provides a mock function for the type MockCanvasTestify
func (_mock *MockCanvasTestify) Group(s ...string) {
	if len(s) > 0 {
		_mock.Called(s)
	} else {
		_mock.Called()
	}

	return
}

// MockCanvas_Group_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Group'
type MockCanvas_Group_Call struct {
	*mock.Call
}

// Group is a helper method to define mock.On call
//   - s ...string
func (_e *MockCanvas_Expecter) Group(s ...interface{}) *MockCanvas_Group_Call {
	return &MockCanvas_Group_Call{Call: _e.mock.On("Group",
		append([]interface{}{}, s...)...)}
}

func (_c *MockCanvas_Group_Call) Run(run func(s ...string)) *MockCanvas_Group_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		var variadicArgs []string
		if len(args) > 0 {
			variadicArgs = args[0].([]string)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockCanvas_Group_Call) Return() *MockCanvas_Group_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCanvas_Group_Call) RunAndReturn(run func(s ...string)) *MockCanvas_Group_Call {
	_c.Run(run)
	return _c
}

// Line provides a mock function for the type MockCanvasTestify
func (_mock *MockCanvasTestify) Line(x1 int, y1 int, x2 int, y2 int, s ...string) {
	if len(s) > 0 {
		_mock.Called(x1, y1, x2, y2, s)
	} else {
		_mock.Called(x1, y1, x2, y2)
	}

	return
}

// MockCanvas_Line_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Line'
type MockCanvas_Line_Call struct {
	*mock.Call
}

// Line is a helper method to define mock.On call
//   - x1 int
//   - y1 int
//   - x2 int
//   - y2 int
//   - s ...string
func (_e *MockCanvas_Expecter) Line(x1 interface{}, y1 interface{}, x2 interface{}, y2 interface{}, s ...interface{}) *MockCanvas_Line_Call {
	return &MockCanvas_Line_Call{Call: _e.mock.On("Line",
		append([]interface{}{x1, y1, x2, y2}, s...)...)}
}

func (_c *MockCanvas_Line_Call) Run(run func(x1 int, y1 int, x2 int, y2 int, s ...string)) *MockCanvas_Line_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 []string
		var variadicArgs []string
		if len(args) > 4 {
			variadicArgs = args[4].([]string)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockCanvas_Line_Call) Return() *MockCanvas_Line_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCanvas_Line_Call) RunAndReturn(run func(x1 int, y1 int, x2 int, y2 int, s ...string)) *MockCanvas_Line_Call {
	_c.Run(run)
	return _c
}

// LineFloat64 provides a mock function for the type MockCanvasTestify
func (_mock *MockCanvasTestify) LineFloat64(x1 float64, y1 float64, x2 float64, y2 float64, s ...string) {
	if len(s) > 0 {
		_mock.Called(x1, y1, x2, y2, s)
	} else {
		_mock.Called(x1, y1, x2, y2)
	}

	return
}

// MockCanvas_LineFloat64_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LineFloat64'
type MockCanvas_LineFloat64_Call struct {
	*mock.Call
}

// LineFloat64 is a helper method to define mock.On call
//   - x1 float64
//   - y1 float64
//   - x2 float64
//   - y2 float64
//   - s ...string
func (_e *MockCanvas_Expecter) LineFloat64(x1 interface{}, y1 interface{}, x2 interface{}, y2 interface{}, s ...interface{}) *MockCanvas_LineFloat64_Call {
	return &MockCanvas_LineFloat64_Call{Call: _e.mock.On("LineFloat64",
		append([]interface{}{x1, y1, x2, y2}, s...)...)}
}

func (_c *MockCanvas_LineFloat64_Call) Run(run func(x1 float64, y1 float64, x2 float64, y2 float64, s ...string)) *MockCanvas_LineFloat64_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 float64
		if args[1] != nil {
			arg1 = args[1].(float64)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		var arg4 []string
		var variadicArgs []string
		if len(args) > 4 {
			variadicArgs = args[4].([]string)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockCanvas_LineFloat64_Call) Return() *MockCanvas_LineFloat64_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCanvas_LineFloat64_Call) RunAndReturn(run func(x1 float64, y1 float64, x2 float64, y2 float64, s ...string)) *MockCanvas_LineFloat64_Call {
	_c.Run(run)
	return _c
}

// Path provides a mock function for the type MockCanvasTestify
func (_mock *MockCanvasTestify) Path(d string, s ...string) {
	if len(s) > 0 {
		_mock.Called(d, s)
	} else {
		_mock.Called(d)
	}

	return
}

// MockCanvas_Path_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Path'
type MockCanvas_Path_Call struct {
	*mock.Call
}

// Path is a helper method to define mock.On call
//   - d string
//   - s ...string
func (_e *MockCanvas_Expecter) Path(d interface{}, s ...interface{}) *MockCanvas_Path_Call {
	return &MockCanvas_Path_Call{Call: _e.mock.On("Path",
		append([]interface{}{d}, s...)...)}
}

func (_c *MockCanvas_Path_Call) Run(run func(d string, s ...string)) *MockCanvas_Path_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockCanvas_Path_Call) Return() *MockCanvas_Path_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCanvas_Path_Call) RunAndReturn(run func(d string, s ...string)) *MockCanvas_Path_Call {
	_c.Run(run)
	return _c
}

// Qbez provides a mock function for the type MockCanvasTestify
func (_mock *MockCanvasTestify) Qbez(sx int, sy int, cx int, cy int, ex int, ey int, s ...string) {
	if len(s) > 0 {
		_mock.Called(sx, sy, cx, cy, ex, ey, s)
	} else {
		_mock.Called(sx, sy, cx, cy, ex, ey)
	}

	return
}

// MockCanvas_Qbez_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Qbez'
type MockCanvas_Qbez_Call struct {
	*mock.Call
}

// Qbez is a helper method to define mock.On call
//   - sx int
//   - sy int
//   - cx int
//   - cy int
//   - ex int
//   - ey int
//   - s ...string
func (_e *MockCanvas_Expecter) Qbez(sx interface{}, sy interface{}, cx interface{}, cy interface{}, ex interface{}, ey interface{}, s ...interface{}) *MockCanvas_Qbez_Call {
	return &MockCanvas_Qbez_Call{Call: _e.mock.On("Qbez",
		append([]interface{}{sx, sy, cx, cy, ex, ey}, s...)...)}
}

func (_c *MockCanvas_Qbez_Call) Run(run func(sx int, sy int, cx int, cy int, ex int, ey int, s ...string)) *MockCanvas_Qbez_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		var arg6 []string
		var variadicArgs []string
		if len(args) > 6 {
			variadicArgs = args[6].([]string)
		}
		arg6 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6...,
		)
	})
	return _c
}

func (_c *MockCanvas_Qbez_Call) Return() *MockCanvas_Qbez_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCanvas_Qbez_Call) RunAndReturn(run func(sx int, sy int, cx int, cy int, ex int, ey int, s ...string)) *MockCanvas_Qbez_Call {
	_c.Run(run)
	return _c
}

// Qbezier provides a mock function for the type MockCanvasTestify
func (_mock *MockCanvasTestify) Qbezier(sx int, sy int, cx int, cy int, ex int, ey int, tx int, ty int, s ...string) {
	if len(s) > 0 {
		_mock.Called(sx, sy, cx, cy, ex, ey, tx, ty, s)
	} else {
		_mock.Called(sx, sy, cx, cy, ex, ey, tx, ty)
	}

	return
}

// MockCanvas_Qbezier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Qbezier'
type MockCanvas_Qbezier_Call struct {
	*mock.Call
}

// Qbezier is a helper method to define mock.On call
//   - sx int
//   - sy int
//   - cx int
//   - cy int
//   - ex int
//   - ey int
//   - tx int
//   - ty int
//   - s ...string
func (_e *MockCanvas_Expecter) Qbezier(sx interface{}, sy interface{}, cx interface{}, cy interface{}, ex interface{}, ey interface{}, tx interface{}, ty interface{}, s ...interface{}) *MockCanvas_Qbezier_Call {
	return &MockCanvas_Qbezier_Call{Call: _e.mock.On("Qbezier",
		append([]interface{}{sx, sy, cx, cy, ex, ey, tx, ty}, s...)...)}
}

func (_c *MockCanvas_Qbezier_Call) Run(run func(sx int, sy int, cx int, cy int, ex int, ey int, tx int, ty int, s ...string)) *MockCanvas_Qbezier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		var arg6 int
		if args[6] != nil {
			arg6 = args[6].(int)
		}
		var arg7 int
		if args[7] != nil {
			arg7 = args[7].(int)
		}
		var arg8 []string
		var variadicArgs []string
		if len(args) > 8 {
			variadicArgs = args[8].([]string)
		}
		arg8 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
			arg8...,
		)
	})
	return _c
}

func (_c *MockCanvas_Qbezier_Call) Return() *MockCanvas_Qbezier_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCanvas_Qbezier_Call) RunAndReturn(run func(sx int, sy int, cx int, cy int, ex int, ey int, tx int, ty int, s ...string)) *MockCanvas_Qbezier_Call {
	_c.Run(run)
	return _c
}

// Rect provides a mock function for the type MockCanvasTestify
func (_mock *MockCanvasTestify) Rect(x int, y int, w int, h int, s ...string) {
	if len(s) > 0 {
		_mock.Called(x, y, w, h, s)
	} else {
		_mock.Called(x, y, w, h)
	}

	return
}

// MockCanvas_Rect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rect'
type MockCanvas_Rect_Call struct {
	*mock.Call
}

// Rect is a helper method to define mock.On call
//   - x int
//   - y int
//   - w int
//   - h int
//   - s ...string
func (_e *MockCanvas_Expecter) Rect(x interface{}, y interface{}, w interface{}, h interface{}, s ...interface{}) *MockCanvas_Rect_Call {
	return &MockCanvas_Rect_Call{Call: _e.mock.On("Rect",
		append([]interface{}{x, y, w, h}, s...)...)}
}

func (_c *MockCanvas_Rect_Call) Run(run func(x int, y int, w int, h int, s ...string)) *MockCanvas_Rect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 []string
		var variadicArgs []string
		if len(args) > 4 {
			variadicArgs = args[4].([]string)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockCanvas_Rect_Call) Return() *MockCanvas_Rect_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCanvas_Rect_Call) RunAndReturn(run func(x int, y int, w int, h int, s ...string)) *MockCanvas_Rect_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockCanvasTestify
func (_mock *MockCanvasTestify) Start(w int, h int, ns ...string) {
	if len(ns) > 0 {
		_mock.Called(w, h, ns)
	} else {
		_mock.Called(w, h)
	}

	return
}

// MockCanvas_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockCanvas_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - w int
//   - h int
//   - ns ...string
func (_e *MockCanvas_Expecter) Start(w interface{}, h interface{}, ns ...interface{}) *MockCanvas_Start_Call {
	return &MockCanvas_Start_Call{Call: _e.mock.On("Start",
		append([]interface{}{w, h}, ns...)...)}
}

func (_c *MockCanvas_Start_Call) Run(run func(w int, h int, ns ...string)) *MockCanvas_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCanvas_Start_Call) Return() *MockCanvas_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCanvas_Start_Call) RunAndReturn(run func(w int, h int, ns ...string)) *MockCanvas_Start_Call {
	_c.Run(run)
	return _c
}

// Text provides a mock function for the type MockCanvasTestify
func (_mock *MockCanvasTestify) Text(x int, y int, t string, s ...string) {
	if len(s) > 0 {
		_mock.Called(x, y, t, s)
	} else {
		_mock.Called(x, y, t)
	}

	return
}

// MockCanvas_Text_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Text'
type MockCanvas_Text_Call struct {
	*mock.Call
}

// Text is a helper method to define mock.On call
//   - x int
//   - y int
//   - t string
//   - s ...string
func (_e *MockCanvas_Expecter) Text(x interface{}, y interface{}, t interface{}, s ...interface{}) *MockCanvas_Text_Call {
	return &MockCanvas_Text_Call{Call: _e.mock.On("Text",
		append([]interface{}{x, y, t}, s...)...)}
}

func (_c *MockCanvas_Text_Call) Run(run func(x int, y int, t string, s ...string)) *MockCanvas_Text_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		var variadicArgs []string
		if len(args) > 3 {
			variadicArgs = args[3].([]string)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockCanvas_Text_Call) Return() *MockCanvas_Text_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCanvas_Text_Call) RunAndReturn(run func(x int, y int, t string, s ...string)) *MockCanvas_Text_Call {
	_c.Run(run)
	return _c
}

// TextUnescaped provides a mock function for the type MockCanvasTestify
func (_mock *MockCanvasTestify) TextUnescaped(x float64, y float64, t string, s ...string) {
	if len(s) > 0 {
		_mock.Called(x, y, t, s)
	} else {
		_mock.Called(x, y, t)
	}

	return
}

// MockCanvas_TextUnescaped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TextUnescaped'
type MockCanvas_TextUnescaped_Call struct {
	*mock.Call
}

// TextUnescaped is a helper method to define mock.On call
//   - x float64
//   - y float64
//   - t string
//   - s ...string
func (_e *MockCanvas_Expecter) TextUnescaped(x interface{}, y interface{}, t interface{}, s ...interface{}) *MockCanvas_TextUnescaped_Call {
	return &MockCanvas_TextUnescaped_Call{Call: _e.mock.On("TextUnescaped",
		append([]interface{}{x, y, t}, s...)...)}
}

func (_c *MockCanvas_TextUnescaped_Call) Run(run func(x float64, y float64, t string, s ...string)) *MockCanvas_TextUnescaped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 float64
		if args[1] != nil {
			arg1 = args[1].(float64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		var variadicArgs []string
		if len(args) > 3 {
			variadicArgs = args[3].([]string)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockCanvas_TextUnescaped_Call) Return() *MockCanvas_TextUnescaped_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCanvas_TextUnescaped_Call) RunAndReturn(run func(x float64, y float64, t string, s ...string)) *MockCanvas_TextUnescaped_Call {
	_c.Run(run)
	return _c
}

// Writer provides a mock function for the type MockCanvasTestify
func (_mock *MockCanvasTestify) Writer() io.Writer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Writer")
	}

	var r0 io.Writer
	if returnFunc, ok := ret.Get(0).(func() io.Writer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}
	return r0
}

// MockCanvas_Writer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Writer'
type MockCanvas_Writer_Call struct {
	*mock.Call
}

// Writer is a helper method to define mock.On call
func (_e *MockCanvas_Expecter) Writer() *MockCanvas_Writer_Call {
	return &MockCanvas_Writer_Call{Call: _e.mock.On("Writer")}
}

func (_c *MockCanvas_Writer_Call) Run(run func()) *MockCanvas_Writer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCanvas_Writer_Call) Return(writer io.Writer) *MockCanvas_Writer_Call {
	_c.Call.Return(writer)
	return _c
}

func (_c *MockCanvas_Writer_Call) RunAndReturn(run func() io.Writer) *MockCanvas_Writer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWriter creates a new instance of MockWriterTestify. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWriterTestify(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWriterTestify {
	mock := &MockWriterTestify{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWriterTestify is an autogenerated mock type for the Writer type
type MockWriterTestify struct {
	mock.Mock
}

type MockWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWriterTestify) EXPECT() *MockWriter_Expecter {
	return &MockWriter_Expecter{mock: &_m.Mock}
}

// Write provides a mock function for the type MockWriterTestify
func (_mock *MockWriterTestify) Write(p []byte) (int, error) {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(p)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *MockWriter_Expecter) Write(p interface{}) *MockWriter_Write_Call {
	return &MockWriter_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *MockWriter_Write_Call) Run(run func(p []byte)) *MockWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWriter_Write_Call) Return(n int, err error) *MockWriter_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockWriter_Write_Call) RunAndReturn(run func(p []byte) (int, error)) *MockWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}
