// Code generated by MockGen. DO NOT EDIT.
// Source: utils\canvas\svg.go

// Package canvas is a generated GoMock package.
package canvas

import (
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDelegator is a mock of Delegator interface.
type MockDelegator struct {
	ctrl     *gomock.Controller
	recorder *MockDelegatorMockRecorder
}

// MockDelegatorMockRecorder is the mock recorder for MockDelegator.
type MockDelegatorMockRecorder struct {
	mock *MockDelegator
}

// NewMockDelegator creates a new mock instance.
func NewMockDelegator(ctrl *gomock.Controller) *MockDelegator {
	mock := &MockDelegator{ctrl: ctrl}
	mock.recorder = &MockDelegatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDelegator) EXPECT() *MockDelegatorMockRecorder {
	return m.recorder
}

// OnBeforeStartWrite mocks base method.
func (m *MockDelegator) OnBeforeStartWrite() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnBeforeStartWrite")
}

// OnBeforeStartWrite indicates an expected call of OnBeforeStartWrite.
func (mr *MockDelegatorMockRecorder) OnBeforeStartWrite() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnBeforeStartWrite", reflect.TypeOf((*MockDelegator)(nil).OnBeforeStartWrite))
}

// OnError mocks base method.
func (m *MockDelegator) OnError(arg0 error) DelegatorErrorFlowControl {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnError", arg0)
	ret0, _ := ret[0].(DelegatorErrorFlowControl)
	return ret0
}

// OnError indicates an expected call of OnError.
func (mr *MockDelegatorMockRecorder) OnError(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnError", reflect.TypeOf((*MockDelegator)(nil).OnError), arg0)
}

// MockCanvas is a mock of Canvas interface.
type MockCanvas struct {
	ctrl     *gomock.Controller
	recorder *MockCanvasMockRecorder
}

// MockCanvasMockRecorder is the mock recorder for MockCanvas.
type MockCanvasMockRecorder struct {
	mock *MockCanvas
}

// NewMockCanvas creates a new mock instance.
func NewMockCanvas(ctrl *gomock.Controller) *MockCanvas {
	mock := &MockCanvas{ctrl: ctrl}
	mock.recorder = &MockCanvasMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCanvas) EXPECT() *MockCanvasMockRecorder {
	return m.recorder
}

// Circle mocks base method.
func (m *MockCanvas) Circle(x, y, r int, s ...string) {
	m.ctrl.T.Helper()
	varargs := []interface{}{x, y, r}
	for _, a := range s {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Circle", varargs...)
}

// Circle indicates an expected call of Circle.
func (mr *MockCanvasMockRecorder) Circle(x, y, r interface{}, s ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{x, y, r}, s...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Circle", reflect.TypeOf((*MockCanvas)(nil).Circle), varargs...)
}

// Def mocks base method.
func (m *MockCanvas) Def() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Def")
}

// Def indicates an expected call of Def.
func (mr *MockCanvasMockRecorder) Def() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Def", reflect.TypeOf((*MockCanvas)(nil).Def))
}

// DefEnd mocks base method.
func (m *MockCanvas) DefEnd() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DefEnd")
}

// DefEnd indicates an expected call of DefEnd.
func (mr *MockCanvasMockRecorder) DefEnd() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefEnd", reflect.TypeOf((*MockCanvas)(nil).DefEnd))
}

// Delegator mocks base method.
func (m *MockCanvas) Delegator() Delegator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delegator")
	ret0, _ := ret[0].(Delegator)
	return ret0
}

// Delegator indicates an expected call of Delegator.
func (mr *MockCanvasMockRecorder) Delegator() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delegator", reflect.TypeOf((*MockCanvas)(nil).Delegator))
}

// End mocks base method.
func (m *MockCanvas) End() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "End")
}

// End indicates an expected call of End.
func (mr *MockCanvasMockRecorder) End() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "End", reflect.TypeOf((*MockCanvas)(nil).End))
}

// Gend mocks base method.
func (m *MockCanvas) Gend() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Gend")
}

// Gend indicates an expected call of Gend.
func (mr *MockCanvasMockRecorder) Gend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gend", reflect.TypeOf((*MockCanvas)(nil).Gend))
}

// Group mocks base method.
func (m *MockCanvas) Group(s ...string) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range s {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Group", varargs...)
}

// Group indicates an expected call of Group.
func (mr *MockCanvasMockRecorder) Group(s ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Group", reflect.TypeOf((*MockCanvas)(nil).Group), s...)
}

// Line mocks base method.
func (m *MockCanvas) Line(x1, y1, x2, y2 int, s ...string) {
	m.ctrl.T.Helper()
	varargs := []interface{}{x1, y1, x2, y2}
	for _, a := range s {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Line", varargs...)
}

// Line indicates an expected call of Line.
func (mr *MockCanvasMockRecorder) Line(x1, y1, x2, y2 interface{}, s ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{x1, y1, x2, y2}, s...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Line", reflect.TypeOf((*MockCanvas)(nil).Line), varargs...)
}

// Path mocks base method.
func (m *MockCanvas) Path(d string, s ...string) {
	m.ctrl.T.Helper()
	varargs := []interface{}{d}
	for _, a := range s {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Path", varargs...)
}

// Path indicates an expected call of Path.
func (mr *MockCanvasMockRecorder) Path(d interface{}, s ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{d}, s...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Path", reflect.TypeOf((*MockCanvas)(nil).Path), varargs...)
}

// Qbez mocks base method.
func (m *MockCanvas) Qbez(sx, sy, cx, cy, ex, ey int, s ...string) {
	m.ctrl.T.Helper()
	varargs := []interface{}{sx, sy, cx, cy, ex, ey}
	for _, a := range s {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Qbez", varargs...)
}

// Qbez indicates an expected call of Qbez.
func (mr *MockCanvasMockRecorder) Qbez(sx, sy, cx, cy, ex, ey interface{}, s ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{sx, sy, cx, cy, ex, ey}, s...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Qbez", reflect.TypeOf((*MockCanvas)(nil).Qbez), varargs...)
}

// Qbezier mocks base method.
func (m *MockCanvas) Qbezier(sx, sy, cx, cy, ex, ey, tx, ty int, s ...string) {
	m.ctrl.T.Helper()
	varargs := []interface{}{sx, sy, cx, cy, ex, ey, tx, ty}
	for _, a := range s {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Qbezier", varargs...)
}

// Qbezier indicates an expected call of Qbezier.
func (mr *MockCanvasMockRecorder) Qbezier(sx, sy, cx, cy, ex, ey, tx, ty interface{}, s ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{sx, sy, cx, cy, ex, ey, tx, ty}, s...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Qbezier", reflect.TypeOf((*MockCanvas)(nil).Qbezier), varargs...)
}

// Start mocks base method.
func (m *MockCanvas) Start(w, h int, ns ...string) {
	m.ctrl.T.Helper()
	varargs := []interface{}{w, h}
	for _, a := range ns {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Start", varargs...)
}

// Start indicates an expected call of Start.
func (mr *MockCanvasMockRecorder) Start(w, h interface{}, ns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{w, h}, ns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockCanvas)(nil).Start), varargs...)
}

// Text mocks base method.
func (m *MockCanvas) Text(x, y int, t string, s ...string) {
	m.ctrl.T.Helper()
	varargs := []interface{}{x, y, t}
	for _, a := range s {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Text", varargs...)
}

// Text indicates an expected call of Text.
func (mr *MockCanvasMockRecorder) Text(x, y, t interface{}, s ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{x, y, t}, s...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Text", reflect.TypeOf((*MockCanvas)(nil).Text), varargs...)
}

// Writer mocks base method.
func (m *MockCanvas) Writer() io.Writer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Writer")
	ret0, _ := ret[0].(io.Writer)
	return ret0
}

// Writer indicates an expected call of Writer.
func (mr *MockCanvasMockRecorder) Writer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Writer", reflect.TypeOf((*MockCanvas)(nil).Writer))
}
