package text

const (
	REFREIN_TEXT_LENGTH = 47
	FINE_TEXT_LENGTH    = 30

	OTHER_TEXT_UPPERCASE_WIDTH = 10
	OTHER_TEXT_LOWERCASE_WIDTH = 5

	TEXT_STAFF_TOP_LINE_GAP_WIDTH = 10
)

const (
	FERMATA_OFFSET     = 15
	REPEAT_LINE_OFFSET = 8
)

const TEXT_BASELINE_DISTANCE = 10
const TEXT_TO_STAFF_DISTANCE = 25

const (
	DEFAULT_TEXT_REFREIN = "Refrein"
	DEFAULT_TEXT_FINE    = "Fine"
)
