// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package text

import (
	"context"

	"github.com/jodi-ivan/numbered-notation-xml/internal/entity"
	"github.com/jodi-ivan/numbered-notation-xml/internal/musicxml"
	"github.com/jodi-ivan/numbered-notation-xml/internal/staff/lines"
	"github.com/jodi-ivan/numbered-notation-xml/utils/canvas"
	mock "github.com/stretchr/testify/mock"
)

// NewMockText creates a new instance of MockText. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockText(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockText {
	mock := &MockText{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockText is an autogenerated mock type for the Text type
type MockText struct {
	mock.Mock
}

type MockText_Expecter struct {
	mock *mock.Mock
}

func (_m *MockText) EXPECT() *MockText_Expecter {
	return &MockText_Expecter{mock: &_m.Mock}
}

// MeasureHasText provides a mock function for the type MockText
func (_mock *MockText) MeasureHasText(measure musicxml.Measure, t string) bool {
	ret := _mock.Called(measure, t)

	if len(ret) == 0 {
		panic("no return value specified for MeasureHasText")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(musicxml.Measure, string) bool); ok {
		r0 = returnFunc(measure, t)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockText_MeasureHasText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MeasureHasText'
type MockText_MeasureHasText_Call struct {
	*mock.Call
}

// MeasureHasText is a helper method to define mock.On call
//   - measure musicxml.Measure
//   - t string
func (_e *MockText_Expecter) MeasureHasText(measure interface{}, t interface{}) *MockText_MeasureHasText_Call {
	return &MockText_MeasureHasText_Call{Call: _e.mock.On("MeasureHasText", measure, t)}
}

func (_c *MockText_MeasureHasText_Call) Run(run func(measure musicxml.Measure, t string)) *MockText_MeasureHasText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 musicxml.Measure
		if args[0] != nil {
			arg0 = args[0].(musicxml.Measure)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockText_MeasureHasText_Call) Return(b bool) *MockText_MeasureHasText_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockText_MeasureHasText_Call) RunAndReturn(run func(measure musicxml.Measure, t string) bool) *MockText_MeasureHasText_Call {
	_c.Call.Return(run)
	return _c
}

// NoteHasText provides a mock function for the type MockText
func (_mock *MockText) NoteHasText(measureText []musicxml.MeasureText, t ...string) bool {
	var tmpRet mock.Arguments
	if len(t) > 0 {
		tmpRet = _mock.Called(measureText, t)
	} else {
		tmpRet = _mock.Called(measureText)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for NoteHasText")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func([]musicxml.MeasureText, ...string) bool); ok {
		r0 = returnFunc(measureText, t...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockText_NoteHasText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NoteHasText'
type MockText_NoteHasText_Call struct {
	*mock.Call
}

// NoteHasText is a helper method to define mock.On call
//   - measureText []musicxml.MeasureText
//   - t ...string
func (_e *MockText_Expecter) NoteHasText(measureText interface{}, t ...interface{}) *MockText_NoteHasText_Call {
	return &MockText_NoteHasText_Call{Call: _e.mock.On("NoteHasText",
		append([]interface{}{measureText}, t...)...)}
}

func (_c *MockText_NoteHasText_Call) Run(run func(measureText []musicxml.MeasureText, t ...string)) *MockText_NoteHasText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []musicxml.MeasureText
		if args[0] != nil {
			arg0 = args[0].([]musicxml.MeasureText)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockText_NoteHasText_Call) Return(b bool) *MockText_NoteHasText_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockText_NoteHasText_Call) RunAndReturn(run func(measureText []musicxml.MeasureText, t ...string) bool) *MockText_NoteHasText_Call {
	_c.Call.Return(run)
	return _c
}

// RenderMeasureText provides a mock function for the type MockText
func (_mock *MockText) RenderMeasureText(ctx context.Context, y int, canv canvas.Canvas, notes []*entity.NoteRenderer, linestaff ...lines.LineStaff) {
	if len(linestaff) > 0 {
		_mock.Called(ctx, y, canv, notes, linestaff)
	} else {
		_mock.Called(ctx, y, canv, notes)
	}

	return
}

// MockText_RenderMeasureText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderMeasureText'
type MockText_RenderMeasureText_Call struct {
	*mock.Call
}

// RenderMeasureText is a helper method to define mock.On call
//   - ctx context.Context
//   - y int
//   - canv canvas.Canvas
//   - notes []*entity.NoteRenderer
//   - linestaff ...lines.LineStaff
func (_e *MockText_Expecter) RenderMeasureText(ctx interface{}, y interface{}, canv interface{}, notes interface{}, linestaff ...interface{}) *MockText_RenderMeasureText_Call {
	return &MockText_RenderMeasureText_Call{Call: _e.mock.On("RenderMeasureText",
		append([]interface{}{ctx, y, canv, notes}, linestaff...)...)}
}

func (_c *MockText_RenderMeasureText_Call) Run(run func(ctx context.Context, y int, canv canvas.Canvas, notes []*entity.NoteRenderer, linestaff ...lines.LineStaff)) *MockText_RenderMeasureText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 canvas.Canvas
		if args[2] != nil {
			arg2 = args[2].(canvas.Canvas)
		}
		var arg3 []*entity.NoteRenderer
		if args[3] != nil {
			arg3 = args[3].([]*entity.NoteRenderer)
		}
		var arg4 []lines.LineStaff
		var variadicArgs []lines.LineStaff
		if len(args) > 4 {
			variadicArgs = args[4].([]lines.LineStaff)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockText_RenderMeasureText_Call) Return() *MockText_RenderMeasureText_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockText_RenderMeasureText_Call) RunAndReturn(run func(ctx context.Context, y int, canv canvas.Canvas, notes []*entity.NoteRenderer, linestaff ...lines.LineStaff)) *MockText_RenderMeasureText_Call {
	_c.Run(run)
	return _c
}

// SetMeasureTextRenderer provides a mock function for the type MockText
func (_mock *MockText) SetMeasureTextRenderer(ctx context.Context, noteRenderer *entity.NoteRenderer, note musicxml.Note, isLastNote bool) bool {
	ret := _mock.Called(ctx, noteRenderer, note, isLastNote)

	if len(ret) == 0 {
		panic("no return value specified for SetMeasureTextRenderer")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.NoteRenderer, musicxml.Note, bool) bool); ok {
		r0 = returnFunc(ctx, noteRenderer, note, isLastNote)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockText_SetMeasureTextRenderer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMeasureTextRenderer'
type MockText_SetMeasureTextRenderer_Call struct {
	*mock.Call
}

// SetMeasureTextRenderer is a helper method to define mock.On call
//   - ctx context.Context
//   - noteRenderer *entity.NoteRenderer
//   - note musicxml.Note
//   - isLastNote bool
func (_e *MockText_Expecter) SetMeasureTextRenderer(ctx interface{}, noteRenderer interface{}, note interface{}, isLastNote interface{}) *MockText_SetMeasureTextRenderer_Call {
	return &MockText_SetMeasureTextRenderer_Call{Call: _e.mock.On("SetMeasureTextRenderer", ctx, noteRenderer, note, isLastNote)}
}

func (_c *MockText_SetMeasureTextRenderer_Call) Run(run func(ctx context.Context, noteRenderer *entity.NoteRenderer, note musicxml.Note, isLastNote bool)) *MockText_SetMeasureTextRenderer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.NoteRenderer
		if args[1] != nil {
			arg1 = args[1].(*entity.NoteRenderer)
		}
		var arg2 musicxml.Note
		if args[2] != nil {
			arg2 = args[2].(musicxml.Note)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockText_SetMeasureTextRenderer_Call) Return(b bool) *MockText_SetMeasureTextRenderer_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockText_SetMeasureTextRenderer_Call) RunAndReturn(run func(ctx context.Context, noteRenderer *entity.NoteRenderer, note musicxml.Note, isLastNote bool) bool) *MockText_SetMeasureTextRenderer_Call {
	_c.Call.Return(run)
	return _c
}
