// Code generated by MockGen. DO NOT EDIT.
// Source: internal\barline\barline.go

// Package barline is a generated GoMock package.
package barline

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/jodi-ivan/numbered-notation-xml/internal/entity"
	musicxml "github.com/jodi-ivan/numbered-notation-xml/internal/musicxml"
	canvas "github.com/jodi-ivan/numbered-notation-xml/utils/canvas"
)

// MockBarline is a mock of Barline interface.
type MockBarline struct {
	ctrl     *gomock.Controller
	recorder *MockBarlineMockRecorder
}

// MockBarlineMockRecorder is the mock recorder for MockBarline.
type MockBarlineMockRecorder struct {
	mock *MockBarline
}

// NewMockBarline creates a new mock instance.
func NewMockBarline(ctrl *gomock.Controller) *MockBarline {
	mock := &MockBarline{ctrl: ctrl}
	mock.recorder = &MockBarlineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBarline) EXPECT() *MockBarlineMockRecorder {
	return m.recorder
}

// GetRendererLeftBarline mocks base method.
func (m *MockBarline) GetRendererLeftBarline(measure musicxml.Measure, x int, lastRightBarlinePosition *entity.Coordinate) (*entity.NoteRenderer, *BarlineInfo) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRendererLeftBarline", measure, x, lastRightBarlinePosition)
	ret0, _ := ret[0].(*entity.NoteRenderer)
	ret1, _ := ret[1].(*BarlineInfo)
	return ret0, ret1
}

// GetRendererLeftBarline indicates an expected call of GetRendererLeftBarline.
func (mr *MockBarlineMockRecorder) GetRendererLeftBarline(measure, x, lastRightBarlinePosition interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRendererLeftBarline", reflect.TypeOf((*MockBarline)(nil).GetRendererLeftBarline), measure, x, lastRightBarlinePosition)
}

// GetRendererRightBarline mocks base method.
func (m *MockBarline) GetRendererRightBarline(measure musicxml.Measure, x int) (int, *entity.NoteRenderer) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRendererRightBarline", measure, x)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(*entity.NoteRenderer)
	return ret0, ret1
}

// GetRendererRightBarline indicates an expected call of GetRendererRightBarline.
func (mr *MockBarlineMockRecorder) GetRendererRightBarline(measure, x interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRendererRightBarline", reflect.TypeOf((*MockBarline)(nil).GetRendererRightBarline), measure, x)
}

// RenderBarline mocks base method.
func (m *MockBarline) RenderBarline(ctx context.Context, canv canvas.Canvas, barline musicxml.Barline, coordinate entity.Coordinate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderBarline", ctx, canv, barline, coordinate)
}

// RenderBarline indicates an expected call of RenderBarline.
func (mr *MockBarlineMockRecorder) RenderBarline(ctx, canv, barline, coordinate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderBarline", reflect.TypeOf((*MockBarline)(nil).RenderBarline), ctx, canv, barline, coordinate)
}
