// Code generated by MockGen. DO NOT EDIT.
// Source: lyric.go

// Package lyric is a generated GoMock package.
package lyric

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/jodi-ivan/numbered-notation-xml/internal/entity"
	musicxml "github.com/jodi-ivan/numbered-notation-xml/internal/musicxml"
	canvas "github.com/jodi-ivan/numbered-notation-xml/utils/canvas"
)

// MockLyric is a mock of Lyric interface.
type MockLyric struct {
	ctrl     *gomock.Controller
	recorder *MockLyricMockRecorder
}

// MockLyricMockRecorder is the mock recorder for MockLyric.
type MockLyricMockRecorder struct {
	mock *MockLyric
}

// NewMockLyric creates a new mock instance.
func NewMockLyric(ctrl *gomock.Controller) *MockLyric {
	mock := &MockLyric{ctrl: ctrl}
	mock.recorder = &MockLyricMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLyric) EXPECT() *MockLyricMockRecorder {
	return m.recorder
}

// CalculateHypen mocks base method.
func (m *MockLyric) CalculateHypen(ctx context.Context, prevLyric, currentLyric *LyricPosition) []entity.Coordinate {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateHypen", ctx, prevLyric, currentLyric)
	ret0, _ := ret[0].([]entity.Coordinate)
	return ret0
}

// CalculateHypen indicates an expected call of CalculateHypen.
func (mr *MockLyricMockRecorder) CalculateHypen(ctx, prevLyric, currentLyric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateHypen", reflect.TypeOf((*MockLyric)(nil).CalculateHypen), ctx, prevLyric, currentLyric)
}

// CalculateLyricWidth mocks base method.
func (m *MockLyric) CalculateLyricWidth(arg0 string) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateLyricWidth", arg0)
	ret0, _ := ret[0].(float64)
	return ret0
}

// CalculateLyricWidth indicates an expected call of CalculateLyricWidth.
func (mr *MockLyricMockRecorder) CalculateLyricWidth(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateLyricWidth", reflect.TypeOf((*MockLyric)(nil).CalculateLyricWidth), arg0)
}

// CalculateMarginLeft mocks base method.
func (m *MockLyric) CalculateMarginLeft(txt string) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateMarginLeft", txt)
	ret0, _ := ret[0].(float64)
	return ret0
}

// CalculateMarginLeft indicates an expected call of CalculateMarginLeft.
func (mr *MockLyricMockRecorder) CalculateMarginLeft(txt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateMarginLeft", reflect.TypeOf((*MockLyric)(nil).CalculateMarginLeft), txt)
}

// CalculateOverallWidth mocks base method.
func (m *MockLyric) CalculateOverallWidth(ls []entity.Lyric) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateOverallWidth", ls)
	ret0, _ := ret[0].(float64)
	return ret0
}

// CalculateOverallWidth indicates an expected call of CalculateOverallWidth.
func (mr *MockLyricMockRecorder) CalculateOverallWidth(ls interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateOverallWidth", reflect.TypeOf((*MockLyric)(nil).CalculateOverallWidth), ls)
}

// RenderElision mocks base method.
func (m *MockLyric) RenderElision(ctx context.Context, canv canvas.Canvas, text []entity.Text, lyricPart int, pos entity.Coordinate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderElision", ctx, canv, text, lyricPart, pos)
}

// RenderElision indicates an expected call of RenderElision.
func (mr *MockLyricMockRecorder) RenderElision(ctx, canv, text, lyricPart, pos interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderElision", reflect.TypeOf((*MockLyric)(nil).RenderElision), ctx, canv, text, lyricPart, pos)
}

// RenderHypen mocks base method.
func (m *MockLyric) RenderHypen(ctx context.Context, canv canvas.Canvas, measure []*entity.NoteRenderer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderHypen", ctx, canv, measure)
}

// RenderHypen indicates an expected call of RenderHypen.
func (mr *MockLyricMockRecorder) RenderHypen(ctx, canv, measure interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderHypen", reflect.TypeOf((*MockLyric)(nil).RenderHypen), ctx, canv, measure)
}

// RenderLyrics mocks base method.
func (m *MockLyric) RenderLyrics(ctx context.Context, canv canvas.Canvas, measure []*entity.NoteRenderer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderLyrics", ctx, canv, measure)
}

// RenderLyrics indicates an expected call of RenderLyrics.
func (mr *MockLyricMockRecorder) RenderLyrics(ctx, canv, measure interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderLyrics", reflect.TypeOf((*MockLyric)(nil).RenderLyrics), ctx, canv, measure)
}

// SetLyricRenderer mocks base method.
func (m *MockLyric) SetLyricRenderer(noteRenderer *entity.NoteRenderer, rawLyric []musicxml.Lyric) VerseInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLyricRenderer", noteRenderer, rawLyric)
	ret0, _ := ret[0].(VerseInfo)
	return ret0
}

// SetLyricRenderer indicates an expected call of SetLyricRenderer.
func (mr *MockLyricMockRecorder) SetLyricRenderer(noteRenderer, rawLyric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLyricRenderer", reflect.TypeOf((*MockLyric)(nil).SetLyricRenderer), noteRenderer, rawLyric)
}

// SplitLyricPrefix mocks base method.
func (m *MockLyric) SplitLyricPrefix(note *entity.NoteRenderer, part int, leftBarline *entity.NoteRenderer) []LyricPosition {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SplitLyricPrefix", note, part, leftBarline)
	ret0, _ := ret[0].([]LyricPosition)
	return ret0
}

// SplitLyricPrefix indicates an expected call of SplitLyricPrefix.
func (mr *MockLyricMockRecorder) SplitLyricPrefix(note, part, leftBarline interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SplitLyricPrefix", reflect.TypeOf((*MockLyric)(nil).SplitLyricPrefix), note, part, leftBarline)
}
