// Code generated by MockGen. DO NOT EDIT.
// Source: internal\lyric\lyric.go

// Package lyric is a generated GoMock package.
package lyric

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/jodi-ivan/numbered-notation-xml/internal/entity"
	musicxml "github.com/jodi-ivan/numbered-notation-xml/internal/musicxml"
	repository "github.com/jodi-ivan/numbered-notation-xml/svc/repository"
	canvas "github.com/jodi-ivan/numbered-notation-xml/utils/canvas"
)

// MockLyric is a mock of Lyric interface.
type MockLyric struct {
	ctrl     *gomock.Controller
	recorder *MockLyricMockRecorder
}

// MockLyricMockRecorder is the mock recorder for MockLyric.
type MockLyricMockRecorder struct {
	mock *MockLyric
}

// NewMockLyric creates a new mock instance.
func NewMockLyric(ctrl *gomock.Controller) *MockLyric {
	mock := &MockLyric{ctrl: ctrl}
	mock.recorder = &MockLyricMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLyric) EXPECT() *MockLyricMockRecorder {
	return m.recorder
}

// CalculateLyricWidth mocks base method.
func (m *MockLyric) CalculateLyricWidth(arg0 string) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateLyricWidth", arg0)
	ret0, _ := ret[0].(float64)
	return ret0
}

// CalculateLyricWidth indicates an expected call of CalculateLyricWidth.
func (mr *MockLyricMockRecorder) CalculateLyricWidth(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateLyricWidth", reflect.TypeOf((*MockLyric)(nil).CalculateLyricWidth), arg0)
}

// RenderVerse mocks base method.
func (m *MockLyric) RenderVerse(ctx context.Context, canv canvas.Canvas, y int, verses []repository.HymnVerse) VerseInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderVerse", ctx, canv, y, verses)
	ret0, _ := ret[0].(VerseInfo)
	return ret0
}

// RenderVerse indicates an expected call of RenderVerse.
func (mr *MockLyricMockRecorder) RenderVerse(ctx, canv, y, verses interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderVerse", reflect.TypeOf((*MockLyric)(nil).RenderVerse), ctx, canv, y, verses)
}

// SetLyricRenderer mocks base method.
func (m *MockLyric) SetLyricRenderer(noteRenderer *entity.NoteRenderer, note musicxml.Note) VerseInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLyricRenderer", noteRenderer, note)
	ret0, _ := ret[0].(VerseInfo)
	return ret0
}

// SetLyricRenderer indicates an expected call of SetLyricRenderer.
func (mr *MockLyricMockRecorder) SetLyricRenderer(noteRenderer, note interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLyricRenderer", reflect.TypeOf((*MockLyric)(nil).SetLyricRenderer), noteRenderer, note)
}
